import {finalUnits,finalRows} from './units56.js?v=macro2';
import {additionalUnits,additionalRows} from './units34.js?v=macro2';
import {importedVocabulary} from './imported.js?v=macro2';
export const units=[{id:1,title:'Basic Economic Concepts',zh:'基本经济概念',description:'Start with choices. Understand how people allocate scarce resources.',color:'green'},{id:2,title:'Supply and Demand',zh:'供给与需求',description:'Read the market. Connect incentives, prices, policy and trade.',color:'blue'},...additionalUnits,...finalUnits];
// Original summaries and practice material aligned to the user-supplied 2020 CED.
const rows=[
['1.1','Scarcity','稀缺性','Limited resources require choices.',
['Scarcity exists because available resources cannot satisfy all wants.','Every choice involves a trade-off: using a resource for one purpose limits other uses.','Land, labor and capital are factors of production. Capital means produced tools and equipment, not simply money.','Established knowledge can be non-rival: one person using an idea does not prevent another from using it.'],
'Even a wealthy economy has limited time, workers and productive resources. Wealth does not eliminate scarcity.','稀缺不是贫穷，也不等于暂时的市场短缺。','Scarcity versus shortage','Scarcity is a persistent constraint on satisfying wants; shortage is quantity demanded exceeding quantity supplied at a particular price.','Limited resources → competing uses → choice → opportunity cost','稀缺是普遍约束；短缺是在某个价格下需求量大于供给量。',
'Scarcity~Limited resources relative to wants.~稀缺性|Trade-off~Giving up some of one objective to obtain more of another.~权衡取舍|Land~Natural resources used in production.~土地与自然资源|Labor~Human effort used to produce goods and services.~劳动|Capital~Produced resources used to make other goods and services.~资本'],
['1.2','Resource Allocation and Economic Systems','资源配置与经济制度','Every economy answers three questions.',
['What goods and services should be produced?','How should those goods and services be produced?','Who will consume the output?','Market economies coordinate through prices and decentralized decisions; command economies rely on central direction.','Mixed economies combine market allocation with government involvement.'],
'A city can allocate transport through private ride services, public buses, or a combination of both.','市场经济也需要产权和制度；混合经济不等于完全由政府计划。','Coordinating scarce resources','Economic systems differ in the institutions and mechanisms used to allocate resources and distribute output.','Economic system → incentives and coordination → production and distribution','经济制度影响生产什么、如何生产以及谁消费。',
'Resource allocation~Assigning scarce resources among competing uses.~资源配置|Market economy~An economy relying mainly on prices and decentralized choices.~市场经济|Command economy~An economy relying mainly on central allocation decisions.~计划经济|Mixed economy~An economy combining markets and government involvement.~混合经济|Property rights~Rules defining ownership and permitted uses of resources.~产权'],
['1.3','Production Possibilities Curve','生产可能性曲线','A boundary shows the cost of choosing.',
['A PPC shows maximum combinations of two outputs possible with current resources and technology.','Points on the curve are productively efficient; inside points show underutilization; outside points are currently unattainable.','Opportunity cost is the output sacrificed divided by the additional output gained.','A straight PPC shows constant opportunity cost; a bowed-out PPC shows increasing opportunity cost. A bowed-in curve can represent decreasing opportunity cost.','More resources or improved productivity can shift the PPC outward; losses can shift it inward. A sector-specific improvement can rotate the frontier.'],
'Moving from 10 books and 0 meals to 8 books and 4 meals costs 2 books, or 0.5 book per meal.','从曲线内移动到曲线上是资源利用改善，不是生产能力增长。','Efficiency versus growth','Using idle resources moves production toward the existing PPC; greater productive capacity shifts the PPC outward.','Idle resources employed → move toward PPC; more capacity → PPC shifts out','区分沿曲线移动、向曲线靠近和整条曲线移动。',
'Production possibilities curve~The frontier of feasible output combinations with current resources and technology.~生产可能性曲线|Opportunity cost~The value of the next best alternative forgone.~机会成本|Productive efficiency~Producing an output combination without wasted productive resources.~生产效率|Economic growth~An increase in productive capacity.~经济增长|Increasing opportunity cost~Successive units of one output require sacrificing more of another.~机会成本递增'],
['1.4','Comparative Advantage and Trade','比较优势与贸易','Specialize where your opportunity cost is lower.',
['Absolute advantage means producing more with the same resources, or using fewer resources for the same output.','Comparative advantage means having a lower opportunity cost.','Use output or input tables carefully: convert the information into opportunity costs before comparing.','Specialization according to comparative advantage creates opportunities for gains from trade.','A mutually beneficial trading ratio lies strictly between the two opportunity costs when both parties are to gain.','Trade can expand consumption possibilities beyond a producer’s own PPC without changing that PPC.'],
'If one unit of cloth costs A 2 wheat and B 4 wheat, exchanging 1 cloth for 3 wheat can benefit both.','绝对优势不决定分工；贸易增加消费可能性，不自动移动生产可能性曲线。','Mutually beneficial trade','Each trading partner gains when the exchange rate is better than its own opportunity cost.','Compare opportunity costs → specialize → exchange between the two costs → gains','先算机会成本，再判断比较优势与交换范围。',
'Absolute advantage~Producing more with the same inputs than another producer.~绝对优势|Comparative advantage~Producing at a lower opportunity cost than another producer.~比较优势|Specialization~Concentrating production on selected goods or tasks.~专业化|Terms of trade~The rate at which one good is exchanged for another.~贸易交换比率|Gains from trade~Increased consumption possibilities made available by exchange.~贸易收益'],
['1.5','Cost-Benefit Analysis','成本收益分析','Choose the alternative with the greatest net benefit.',
['Economic costs include both explicit payments and implicit opportunity costs.','An implicit cost is the value of a forgone alternative without a direct payment.','Consumers evaluate benefits through utility; firms receive total revenue.','Total net benefit equals total benefit minus total cost.','Compare complete alternatives when a decision cannot meaningfully be divided into increments.'],
'A project gives benefits of $120 and costs of $80: net benefit is $40. Another gives $160 and costs $130: net benefit is $30. Choose the first.','收益最大不等于净收益最大；不要漏掉隐性成本。','Explicit and implicit costs','Total economic cost includes direct payments and the opportunity cost of resources supplied without an explicit payment.','Explicit cost + implicit cost → economic cost; benefit − cost → net benefit','显性成本加隐性成本，才是完整的经济成本。',
'Explicit cost~A direct monetary payment for a resource.~显性成本|Implicit cost~An opportunity cost without a direct monetary payment.~隐性成本|Total benefit~The overall benefit obtained from an activity.~总收益或总利益|Total net benefit~Total benefit minus total cost.~总净收益|Utility~Satisfaction obtained from consumption.~效用'],
['1.6','Marginal Analysis and Consumer Choice','边际分析与消费者选择','Think about the next unit, not the average.',
['Rational consumers maximize utility subject to income and other constraints.','Marginal benefit and marginal cost measure the change from one additional unit of an activity.','Expand an activity when MB exceeds MC; reduce it when MC exceeds MB. An interior optimum commonly occurs at MB = MC.','With discrete choices, take the last unit whose additional benefit covers its additional cost.','Marginal utility typically diminishes as more of a good is consumed.','Allocate a budget by comparing MU/P across goods; at a divisible interior optimum, the ratios are equal.','Sunk costs do not change the benefits and costs of current alternatives. Indifference curves are outside this syllabus.'],
'If MU of tea is 12 at $3 and MU of coffee is 10 at $5, tea gives 4 utility per dollar versus 2 for coffee. Shift spending toward tea.','比较 MU/P 而不是只比较 MU；沉没成本不影响当前选择。','Utility per dollar','A consumer improves a feasible bundle by moving spending toward the good with higher marginal utility per dollar.','Calculate MU/P → compare ratios → reallocate spending → maximize utility','每一元带来的边际效用才是比较基础。',
'Marginal benefit~The additional benefit from one more unit of an activity.~边际收益|Marginal cost~The additional cost from one more unit of an activity.~边际成本|Marginal utility~The additional utility from another unit consumed.~边际效用|Diminishing marginal utility~Marginal utility falls as consumption of a good increases.~边际效用递减|Sunk cost~A past cost that cannot be recovered.~沉没成本'],
['2.1','Demand','需求','A price change moves along; other changes shift.',
['The law of demand states that quantity demanded falls as own-price rises, other things equal.','Substitution effects, income effects and diminishing marginal utility explain downward-sloping demand.','Own-price changes cause movements along demand; changes in other determinants shift the curve.','Demand determinants include income, tastes, related goods’ prices, expectations and the number of buyers.','Income increases demand for normal goods but decreases demand for inferior goods.','Market demand is the horizontal sum of individual quantities at each price. Property rights and constraints support market choices.'],
'A higher price of tea raises demand for substitute coffee. A higher price of coffee itself reduces quantity demanded along its demand curve.','需求变化与需求量变化不同；不要因本商品价格变化移动需求曲线。','Demand shifts','A change in a non-price determinant changes the quantity buyers want at each possible own-price.','Non-price determinant changes → demand shifts → new market equilibrium','非价格因素变化才会移动整条需求曲线。',
'Demand~The quantities buyers are willing and able to buy at different prices.~需求|Quantity demanded~The amount buyers want at a particular price.~需求量|Normal good~A good whose demand rises when income rises.~正常品|Inferior good~A good whose demand falls when income rises.~劣等品|Substitution effect~A response to a change in a good’s relative price.~替代效应'],
['2.2','Supply','供给','Production incentives shape what sellers offer.',
['The law of supply states that quantity supplied rises as own-price rises, other things equal.','An own-price change causes a movement along supply.','Input costs, technology, taxes, subsidies, expectations and seller numbers can shift supply.','Lower production costs increase supply; higher production costs decrease supply.','Market supply is the horizontal sum of firms’ quantities at each price.'],
'Cheaper fertilizer increases the supply of wheat. A higher wheat price increases quantity supplied along the existing curve.','生产成本下降是供给增加，不是需求增加。','Costs and supply','Lower marginal production costs make sellers willing to supply more at a given price.','Input cost falls → supply shifts right → price falls and quantity rises','成本降低 → 供给右移 → 均衡价格下降、数量上升。',
'Supply~The quantities sellers are willing and able to sell at different prices.~供给|Quantity supplied~The amount sellers offer at a particular price.~供给量|Input cost~The price paid for a resource used in production.~投入成本|Technology~Methods for transforming inputs into output.~技术|Market supply~Total quantity all sellers offer at each price.~市场供给'],
['2.3','Price Elasticity of Demand','需求价格弹性','Measure responsiveness, not steepness alone.',
['PED equals percentage change in quantity demanded divided by percentage change in price; classification uses its absolute value.','Elastic demand has |PED| > 1; inelastic demand has |PED| < 1; unit-elastic demand has |PED| = 1.','Perfectly inelastic demand is vertical; perfectly elastic demand is horizontal.','Elasticity is not slope: elasticity varies along a downward-sloping straight demand line.','Close substitutes, time to adjust and the budget share can affect responsiveness.','For elastic demand, price and total revenue move oppositely; for inelastic demand they move together. With unit elasticity, total revenue is unchanged.'],
'A 10% price increase reduces quantity demanded by 20%. |PED| = 2, so demand is elastic and revenue falls.','百分比变化之比不是数量变化除以价格变化。','Elasticity and total revenue','The quantity response determines whether a price change raises or lowers total revenue, P × Q.','Classify elasticity → compare price and quantity effects → predict revenue','富有弹性时，价格与总收益反向变化。',
'Price elasticity of demand~Percentage quantity-demanded change divided by percentage price change.~需求价格弹性|Elastic demand~Demand with an absolute price elasticity greater than one.~富有弹性的需求|Inelastic demand~Demand with an absolute price elasticity below one.~缺乏弹性的需求|Unit-elastic demand~Demand with an absolute price elasticity equal to one.~单位弹性需求|Total revenue~Price multiplied by quantity sold.~总收益'],
['2.4','Price Elasticity of Supply','供给价格弹性','How quickly can production respond?',
['PES equals percentage change in quantity supplied divided by percentage change in price.','Classify supply as elastic, inelastic or unit elastic using the benchmark of one.','Vertical supply is perfectly inelastic; horizontal supply is perfectly elastic.','Production flexibility, access to alternative inputs and adjustment time influence elasticity.','More time to adjust often makes supply more elastic.'],
'Price rises 5% and quantity supplied rises 15%. PES = 3, so supply is elastic.','弹性衡量百分比响应，不能只凭不同单位下的曲线斜率判断。','Time and responsiveness','Producers often have more ways to adjust output when given more time.','More adjustment time → more feasible input changes → greater responsiveness','短期难以增加产能的产品，供给往往更缺乏弹性。',
'Price elasticity of supply~Percentage quantity-supplied change divided by percentage price change.~供给价格弹性|Elastic supply~Supply with price elasticity greater than one.~富有弹性的供给|Inelastic supply~Supply with price elasticity below one.~缺乏弹性的供给|Perfectly inelastic supply~Supply whose quantity does not respond to price changes.~完全无弹性供给|Perfectly elastic supply~Supply represented by a horizontal curve at a given price.~完全弹性供给'],
['2.5','Other Elasticities','其他弹性','The sign tells you the relationship.',
['Income elasticity equals percentage change in quantity demanded divided by percentage change in income.','Positive income elasticity identifies a normal good; negative income elasticity identifies an inferior good.','Cross-price elasticity equals percentage change in demand quantity of X divided by percentage change in price of Y.','Positive cross-price elasticity identifies substitutes; negative identifies complements; zero indicates no response.','Elasticity can be applied to determinants other than own-price.'],
'If a 10% rise in tea’s price raises coffee demand by 5%, cross-price elasticity is +0.5: tea and coffee are substitutes.','收入弹性和交叉价格弹性的正负号不能丢掉。','Signs of cross-price elasticity','Substitutes have positive cross-price elasticity; complements have negative cross-price elasticity.','Price of Y changes → observe demand for X → calculate signed ratio','替代品为正，互补品为负；注意分母是哪种商品的价格。',
'Income elasticity~Percentage quantity-demanded change divided by percentage income change.~需求收入弹性|Cross-price elasticity~Percentage change in quantity demanded of X divided by percentage change in price of Y.~需求交叉价格弹性|Substitutes~Goods that can be used in place of one another.~替代品|Complements~Goods used together.~互补品|Unrelated goods~Goods with no cross-price demand response in the situation analyzed.~无关商品'],
['2.6','Market Equilibrium and Consumer and Producer Surplus','市场均衡与经济剩余','At equilibrium, buyers and sellers agree on quantity.',
['Market equilibrium occurs where quantity demanded equals quantity supplied.','The equilibrium price communicates information and guides allocation.','Consumer surplus is willingness to pay minus the price paid, summed over purchased units.','Producer surplus is receipts minus the minimum sellers would accept, summed over sold units.','Total economic surplus equals consumer surplus plus producer surplus.','Without market failures, competitive equilibrium maximizes total economic surplus. For linear curves, use triangle areas where appropriate.'],
'If maximum willingness to pay is $20, market price is $12 and Q is 8, linear-demand consumer surplus is ½ × 8 × (20 − 12) = $32.','生产者剩余不是利润；有固定成本时两者不同。','Gains from exchange','Trades create surplus when a buyer’s willingness to pay exceeds the seller’s opportunity cost.','Willingness to pay > cost → beneficial trade → total surplus increases','需求曲线下、价格线上是消费者剩余；价格线下、供给线上是生产者剩余。',
'Equilibrium~A market outcome at which quantity demanded equals quantity supplied.~市场均衡|Consumer surplus~Willingness to pay minus actual payment across purchased units.~消费者剩余|Producer surplus~Seller receipts minus the minimum acceptable amount across sold units.~生产者剩余|Total economic surplus~The sum of consumer and producer surplus.~总经济剩余|Allocative efficiency~Producing where marginal social benefit equals marginal social cost.~配置效率'],
['2.7','Market Disequilibrium and Changes in Equilibrium','市场失衡与均衡变化','Trace each shift before combining the effects.',
['A shortage occurs when quantity demanded exceeds quantity supplied; it creates upward price pressure.','A surplus occurs when quantity supplied exceeds quantity demanded; it creates downward price pressure.','Demand increases raise equilibrium price and quantity, with supply unchanged.','Supply increases lower equilibrium price and raise quantity, with demand unchanged.','When both curves shift, one outcome may be indeterminate without relative shift magnitudes.','Changes in surplus depend on the new curves and equilibrium; elasticity affects the size of adjustments.'],
'If demand and supply both increase, quantity rises but the price change is ambiguous without more information.','短缺与过剩是数量差；供需同时变化时不要强行确定两个结果。','Returning to equilibrium','A market imbalance gives buyers and sellers incentives that move price toward market-clearing levels.','Shortage → upward price pressure → QD falls and QS rises → equilibrium','短缺推动涨价，过剩推动降价，直到市场出清。',
'Shortage~Quantity demanded exceeds quantity supplied at the current price.~短缺|Surplus~Quantity supplied exceeds quantity demanded at the current price.~过剩|Disequilibrium~A market condition with unequal quantities demanded and supplied.~非均衡|Market clearing~A price at which quantity demanded equals quantity supplied.~市场出清|Indeterminate outcome~An outcome whose direction needs additional information.~无法确定的结果'],
['2.8','The Effects of Government Intervention in Markets','政府干预对市场的影响','Follow the wedge, then account for welfare.',
['A binding price ceiling is below equilibrium and can create a shortage.','A binding price floor is above equilibrium and can create a surplus.','A per-unit tax creates a wedge between the buyer’s price and the seller’s net price and usually reduces trade.','Tax revenue equals the per-unit tax multiplied by the quantity traded after tax.','The relatively less elastic side bears more of the tax burden, regardless of who legally remits it.','Subsidies change incentives and create government expenditure. Quantity controls can also restrict exchange.','Intervening in an otherwise efficient market can reduce total surplus and create deadweight loss.'],
'A $3 tax reduces sales to 40 units. Revenue is $120. If the old price was $10 and buyers now pay $12, buyers bear $2 and sellers bear $1 per unit.','税负取决于弹性，不取决于法律上由谁向政府缴税。','Binding price controls','A price ceiling constrains prices only below equilibrium; a price floor constrains prices only above equilibrium.','Binding ceiling → price below equilibrium → QD > QS → shortage','有效最高限价在均衡价以下；有效最低限价在均衡价以上。',
'Price ceiling~A legal maximum price.~最高限价|Price floor~A legal minimum price.~最低限价|Per-unit tax~A fixed tax amount applied to each unit traded.~单位税|Subsidy~A government payment that changes production or consumption incentives.~补贴|Deadweight loss~Total economic surplus lost because quantity differs from the efficient level.~无谓损失'],
['2.9','International Trade and Public Policy','国际贸易与公共政策','Compare the world price with the domestic price.',
['If the world price is below the closed-economy price, a price-taking economy imports. If above, it exports.','Imports equal domestic quantity demanded minus domestic quantity supplied at the world price.','Exports equal domestic quantity supplied minus domestic quantity demanded at the world price.','Trade changes consumer and producer surplus and creates net gains in the standard competitive model.','An import tariff raises domestic price, increases domestic production, lowers domestic consumption and reduces imports in the small-country model.','Tariff revenue equals the tariff times post-tariff imports; tariffs create production and consumption deadweight losses.','An import quota limits import quantity. Understanding its effects is required; graphing quotas is excluded.'],
'At the world price, domestic consumers buy 90 and producers supply 30, so imports are 60. If a $2 tariff leaves imports of 40, revenue is $80.','关税收入按征税后的进口量计算，不是国内总消费量。','Tariffs and welfare','A tariff protects domestic producers but raises consumer prices and creates efficiency losses in the small-country model.','Tariff → domestic price rises → production rises and consumption falls → imports fall','进口关税使消费者受损、国内生产者受益，并产生政府收入与无谓损失。',
'World price~The price at which a small economy can trade internationally.~世界价格|Imports~Goods purchased from producers abroad.~进口|Exports~Goods sold to buyers abroad.~出口|Tariff~A tax on imported goods.~关税|Import quota~A limit on the quantity of a good that may be imported.~进口配额']
];
rows.push(...additionalRows,...finalRows);
export const topics=rows.map((r)=>({id:r[0],unit:Number(r[0][0]),title:r[1],zh:r[2],summary:r[3],points:r[4],example:r[5],mistake:r[6],conceptTitle:r[7],definition:r[8],logic:r[9].split(' → '),explanation:r[10]}));
const baseVocabulary=rows.flatMap(r=>r[11].split('|').map((v,i)=>{const [term,definition,zh]=v.split('~');return {id:`v-${r[0]}-${i+1}`,topic:r[0],unit:Number(r[0][0]),term,definition,zh,example:r[5],mistake:r[6]};}));
export const concepts=topics.flatMap(t=>[{id:`c-${t.id}-1`,topic:t.id,unit:t.unit,title:t.title,definition:t.summary,points:t.points,logic:[],zh:t.zh,example:t.example,mistake:t.mistake},{id:`c-${t.id}-2`,topic:t.id,unit:t.unit,title:t.conceptTitle,definition:t.definition,points:[t.definition],logic:t.logic,zh:t.explanation,example:t.example,mistake:t.mistake}]);
export const errors={V1:['Keyword unfamiliar','不认识关键词'],V2:['Terms confused','易混词混淆'],C1:['Definition unclear','定义不清'],C2:['Cause and effect','因果关系错误'],G1:['Axes reversed','横纵轴错误'],G2:['Wrong curve','曲线识别错误'],G3:['Wrong shift','曲线移动错误'],G4:['Equilibrium change','均衡变化错误'],G5:['Missing graph label','图表标签不完整'],M1:['Wrong formula','公式错误'],M2:['Calculation error','计算过程错误'],L1:['Reasoning gap','推理链断裂'],P1:['Policy direction','政策方向错误']};

const normalizeTerm=s=>s.toLowerCase().replace(/[^a-z]/g,'');
const aliases={'lawofincreasingopportunitycost':'increasingopportunitycost','incomeelasticityofdemand':'incomeelasticity','crosspriceelasticity':'crosspriceelasticity','excisetax':'perunittax','quota':'importquota'};
export const vocabulary=[...baseVocabulary];
for(const source of importedVocabulary){
 const norm=normalizeTerm(source.term); const existing=vocabulary.find(v=>normalizeTerm(v.term)===(aliases[norm]||norm));
 if(existing){existing.source='Your vocabulary game';existing.sourceUrl='https://pjmarymeer-lab.github.io/ap-microeconomics-words-game/';existing.sourceDefinition=source.definition;}
 else if(source.topic){const t=topics.find(t=>t.id===source.topic);vocabulary.push({id:'v-import-'+norm,topic:t.id,unit:t.unit,term:source.term,definition:source.definition,zh:source.zh,example:t.example,mistake:t.mistake,source:'Your vocabulary game',sourceUrl:'https://pjmarymeer-lab.github.io/ap-microeconomics-words-game/'});}
}
