// Specific explanations replace broad chapter hints retained by the source website.
export const explanationCorrections={
1:['Resources cannot produce everything people want. That gap makes choice necessary.','资源生产能力不足以满足所有需求，因此存在稀缺。'],
2:['Economics studies how people allocate scarce resources among competing uses.','经济学研究如何在相互竞争的用途间配置稀缺资源。'],
3:['Limited resources relative to wants are the universal allocation problem, even when inflation or unemployment is absent.','即使没有通胀或失业，资源相对需求有限的问题依然存在。'],
4:['Established knowledge is non-rival: one factory using an idea need not prevent another from using it.','已有知识可被多个工厂同时使用，具有非竞争性。'],
5:['By choosing college, Gloria gives up wages she could have earned. Those forgone wages are an implicit opportunity cost.','选择大学意味着放弃本可获得的工资，这属于隐性机会成本。'],
6:['With fixed resources fully employed, more X requires moving resources away from Y, reducing Y output.','资源已充分有效利用时，增加 X 必须减少 Y。'],
7:['On the frontier, fixed resources cannot increase one output without reducing the other.','固定资源下，PPC 上增加一种产出必须减少另一种。'],
8:['A command economy relies more on centralized planning than on decentralized price signals.','计划经济主要依靠集中规划。'],
9:['Households sell factor services and buy goods; businesses buy factor services and sell goods.','家庭提供生产要素并购买商品，企业购买要素并提供商品。'],
10:['Public ownership of productive resources is associated with command allocation.','生产资料公有与计划经济相联系。'],
11:['Market production responds to the interaction of buyers and sellers, rather than buyers or central planners alone.','市场经济产量由买卖双方共同作用决定。'],
12:['Government planners allocate resources in a command economy.','计划经济依赖政府配置资源。'],
15:['A bowed-out PPC becomes steeper as X output rises: each extra X costs more Y.','向外弯曲的 PPC 表示机会成本递增。'],
16:['One hundred X replace one thousand Y, so each X costs 1,000/100 = 10 Y. The straight line makes this cost constant.','每单位 X 的机会成本为 1000÷100＝10 Y，且保持不变。'],
17:['More available labor expands productive capacity for both goods. Reducing unemployment uses existing capacity instead.','劳动总量增加扩大生产能力；降低失业只是改善资源利用。'],
18:['Efficient full employment puts production on the frontier. With capacity unchanged, producing more of one good costs some of the other.','位于 PPC 上时，增产一种商品须减少另一种。'],
20:['Martin makes twelve shirts versus nine with the same resources, establishing absolute advantage. No second-good information establishes comparative advantage.','同投入产出更多说明绝对优势；没有另一商品信息，不能判定比较优势。'],
21:['Comparative advantage requires lower opportunity cost, not greater absolute output. Italy need not have absolute advantage.','比较优势不要求同时具有绝对优势。'],
24:['Specialization and trade can let a country consume beyond its own PPC; its production still lies within its productive capacity.','贸易使消费可能超出 PPC，但生产仍受产能限制。'],
25:['Four window jobs take ten hours. Ten hours could instead mow two lawns, so their forgone pay is the opportunity cost.','洗四家窗需 10 小时，本可割两家草坪。'],
26:['Bread costs Beta 4/2 = 2 tea and Zeta 9/3 = 3 tea. Beta has comparative advantage in bread.','Beta 每面包成本 2 茶，Zeta 为 3 茶，因此 Beta 有比较优势。'],
27:['The ticket costs $50 and forgone wages are 4 × $10 = $40. With no resale alternative, total cost is $90.','票价 50 加放弃工资 40，总经济成本为 90。'],
28:['Building is worthwhile when relevant total benefits exceed total costs, making net benefit positive.','总收益超过总成本时，建桥具有正净收益。'],
29:['At a divisible interior consumer optimum, marginal utility per dollar is equal across goods, subject to the budget.','在预算约束下，内点最优满足每元边际效用相等。'],
30:['Reallocate spending from Y toward X because the last dollar spent on X gives more additional utility.','将支出从 Y 转向每元边际效用更高的 X。'],
31:['Candy yields 10/2 = 5 utils per dollar; chips yield 12/3 = 4. Buy more candy and fewer chips.','糖果每元 5 效用，薯片每元 4 效用，应转向糖果。'],
34:['A higher phone price raises demand for players, so buyers substitute between them.','一种商品涨价增加另一种需求，说明两者是替代品。'],
35:['Lower income reduces demand for a normal good. A change in milk’s own price moves along demand instead.','正常品收入下降使需求减少；自身价格变化只改变需求量。'],
36:['An increase in milk’s own price reduces quantity demanded along the existing demand curve.','牛奶自身涨价导致沿需求曲线的需求量下降。'],
37:['A cheaper complementary good encourages consumption of both goods, increasing demand for the normal good here.','互补品降价增加相关商品需求。'],
38:['Other things equal, a higher own-price leads to a lower quantity demanded, not a shift of demand.','其他不变时，本品价格上升导致需求量下降。'],
39:['A lower milk price reduces quantity supplied along supply. An input-cost change would shift supply.','本品降价导致供给量下降；成本变化才移动供给。'],
40:['Higher industry wages raise automobile production costs, shifting automobile supply left.','工资提高增加生产成本，使汽车供给左移。'],
41:['Cheaper energy lowers production costs and increases supply at every output price.','能源成本下降使各价格下供给量增加。'],
42:['A decrease in own-price reduces quantity supplied along the existing supply curve.','本商品降价使供给量减少，而不是供给曲线移动。'],
43:['Add each firm’s quantity at the same price: this is horizontal summation.','市场供给是同一价格下各企业供给量的横向加总。'],
45:['Both shifts increase quantity. Demand raises price but supply lowers it, so price is indeterminate.','供需同时增加使数量增加；对价格作用相反，方向不确定。'],
46:['Lower popcorn supply raises its price. Buyers switch toward pretzels, raising pretzel demand and price.','爆米花供给减少后涨价，促进替代品椒盐卷饼需求与价格上升。'],
47:['Unfavorable health information reduces demand for oranges, lowering equilibrium price with supply unchanged.','不利健康信息降低橙子需求，均衡价下降。'],
48:['A floor above equilibrium raises quantity supplied and lowers quantity demanded, creating excess supply.','高于均衡价的最低限价产生过剩。'],
49:['With elastic demand, the percentage increase in sales exceeds the percentage price decrease, raising revenue.','富有弹性时，降价引起更大的数量增加，总收益上升。'],
50:['When demand is elastic, a price reduction increases total revenue.','富有弹性时降价提高总收益。'],
51:['Moving down a linear demand curve, the price-to-quantity ratio falls: elasticity goes from elastic through unit elastic to inelastic.','沿直线需求曲线向右下移动，弹性由大于 1 到等于 1 再到小于 1。'],
52:['Revenue is $8 × 400 = $3,200 and $4 × 800 = $3,200. Midpoint percentage changes have equal magnitude, so arc elasticity is one.','两端总收益均为 3200；中点法计算的区间弹性为 1。'],
53:['More close substitutes make it easier for buyers to switch when price changes, increasing demand elasticity.','替代品越多，消费者越容易转向其他商品，需求越有弹性。'],
54:['Absolute elasticity is 10%/40% = 0.25, so demand is inelastic.','需求弹性绝对值为 0.25，缺乏弹性。'],
55:['Quantity demanded changes by −0.5 × 20% = −10%.','需求量下降 10%。'],
56:['No new original Michelangelo sculptures can be produced. A fixed stock has perfectly inelastic supply.','原作存量无法通过继续生产增加，对应完全无弹性供给。'],
57:['Quantity rises by a larger percentage than price. Using midpoint changes, PES = (20/50)/(1/4.5) = 1.8, so supply is elastic.','中点法供给弹性为 1.8，大于 1。'],
58:['With PES = 3, a −10% price change produces a −30% quantity-supplied change.','供给弹性为 3，价格下降 10% 时供给量下降 30%。'],
59:['Quantity supplied changes by 0.5 × (−30%) = −15%.','供给量下降 15%。'],
60:['PES = 20%/10% = 2. This describes supply, not demand.','供给弹性为 2，不能据此判断需求弹性。'],
61:['Negative income elasticity means inferior; negative cross-price elasticity means complementary.','收入弹性为负说明劣等品，交叉弹性为负说明互补。'],
62:['Apple juice quantity rises 10% when orange juice price rises 20%: cross-price elasticity is +0.5.','交叉价格弹性＝10%÷20%＝+0.5。'],
63:['The negative cross-price coefficient indicates complements. A higher price of one lowers demand for the other.','交叉价格弹性为负说明互补，一方涨价降低另一方需求。'],
64:['The response of J is (−3) × (−20%) = +60%.','J 的需求量变化为 −3×−20%＝+60%。'],
65:['Negative income elasticity identifies an inferior good: higher income reduces its demand.','收入弹性为负，收入上升使该商品需求减少。'],
66:['Income elasticity of 5 gives a 50% quantity response to a 10% income increase.','收入增加 10% 时，需求量增加 50%。'],
67:['A minimum below the equilibrium price is nonbinding, so the original equilibrium remains possible.','低于均衡价的最低限价无约束力，不改变均衡。'],
68:['Binding controls move an initially efficient market away from its unconstrained equilibrium and reduce allocative efficiency.','有效管制使原本有效率的市场偏离均衡，降低配置效率。'],
74:['Horizontal supply has no producer-surplus area. It stays zero when input costs fall and supply shifts downward.','水平供给对应生产者剩余为零，成本下降后仍为零。'],
75:['The outage raises demand. Holding price below the new clearing price creates excess demand and a shortage.','停电使需求增加；禁止涨价使价格低于新均衡，产生短缺。'],
79:['Tax revenue = $4 × 950 = $3,800. For linear curves, DWL = ½ × $4 × 50 = $100.','税收 3800；无谓损失＝½×4×50＝100。'],
80:['Buyers pay the seller’s $11 net receipt plus the $4 tax, or $15. Buyers bear $3 and sellers $1 relative to the original $12.','买方支付 11＋4＝15；买方负担 3，卖方负担 1。'],
81:['A sales tax raises buyer price and lowers seller net price, reducing both surpluses. Government revenue does not recover the entire loss: DWL remains.','税收减少消费者和生产者剩余；计入政府收入后仍有无谓损失。'],
82:['A tariff raises the domestic cloth price, reducing domestic consumers’ surplus.','关税提高国内布价，减少消费者剩余。'],
83:['The higher tariff-inclusive price encourages domestic tea producers to expand output.','含关税价格提高，刺激国内茶叶生产增加。'],
84:['Trade at a lower world price reduces domestic producers’ price and sales, reducing their surplus; domestic consumers benefit.','世界价更低时进口，国内生产者价格及销量下降，生产者剩余减少。']
};
