export const monopolisticCompetitionModel={demand:q=>65-.5*q,mr:q=>65-q,atc:q=>720/q+21.5+.005*q*q,mc:q=>21.5+.015*q*q};
const make=(id,level,topic,model,prompt,fields,expected,explanation,zh)=>({id,level,topic,unit:Number(topic[0]),model,prompt,fields,expected,explanation,zh,target:100});
const axes={x:['Quantity','Labor','Price / cost'],y:['Price / cost','Quantity','Output']};
export const additionalGraphs=[
make('g34-production-axes',1,'3.1','production','Label the total product of labor graph with capital held fixed.',{x:['Labor','Quantity','Price / cost'],y:['Output','Price / cost','Labor']},{x:'Labor',y:'Output'},'Total product plots total output against labor when other inputs are fixed.','劳动为横轴，总产量为纵轴。'),
make('g34-production-slope',2,'3.1','production','To the right of I, total product rises with a falling slope. Marginal product is:',{curve:['Positive and falling','Negative','Zero throughout','Positive and rising']},{curve:'Positive and falling'},'The slope of total product is marginal product. A positive but declining slope means positive, falling MP.','总产量斜率就是边际产量；斜率为正但递减。'),
make('g34-shutdown',2,'3.6','shutdown','The horizontal price line lies below minimum AVC. Select the short-run decision.',{outcome:['Shut down; lose unavoidable fixed cost','Produce where P = ATC','Produce because fixed cost exists']},{outcome:'Shut down; lose unavoidable fixed cost'},'No positive output covers variable cost, so produce zero and pay unavoidable fixed cost.','价格低于最低 AVC，停产并承担不可避免固定成本。'),
make('g34-loss',4,'3.6','competitive-loss','Complete this loss-minimizing competitive firm diagram.',{...axes,curves:['MC + ATC + AVC + P = MR','Demand + MR only'],label:['q* at rising MC = P','q* at minimum ATC'],outcome:['Operate because AVC < P < ATC','Shut down because P < ATC','Earn positive profit']},{x:'Quantity',y:'Price / cost',curves:'MC + ATC + AVC + P = MR',label:'q* at rising MC = P',outcome:'Operate because AVC < P < ATC'},'At q*, price covers AVC but not ATC. Operating loses less than shutting down; the shaded rectangle is the loss.','价格覆盖 AVC 但低于 ATC；短期生产的亏损小于停产。'),
make('g34-cost-axes',1,'3.2','costs','Label the axes of the short-run cost diagram.',axes,{x:'Quantity',y:'Price / cost'},'Cost per unit is vertical; output is horizontal. These are not total-cost curves.','纵轴是单位成本，横轴是产量。'),
make('g34-cost-curves',2,'3.2','costs','Identify the curve labeled A, which lies above AVC.',{curve:['ATC','AVC','MC','Demand']},{curve:'ATC'},'ATC = AVC + AFC, so ATC lies above AVC at positive output.','ATC = AVC + AFC，因此 ATC 在 AVC 上方。'),
make('g34-fixed-shift',3,'3.2','costs','A fixed license fee increases. Select the affected average-cost curve and its direction.',{curve:['ATC','AVC','MC'],direction:['Up','Down']},{curve:'ATC',direction:'Up'},'ATC rises. AVC and MC stay unchanged because the fee does not depend on output.','固定成本提高 ATC，不移动 MC 和 AVC。'),
make('g34-cost-build',4,'3.2','costs','Build the short-run cost model with the correct cost relationship.',{...axes,curves:['MC + ATC + AVC','Demand + MR','LRATC'],outcome:['MC crosses averages at their minima','ATC lies below AVC','Fixed cost changes MC']},{x:'Quantity',y:'Price / cost',curves:'MC + ATC + AVC',outcome:'MC crosses averages at their minima'},'MC crosses AVC and ATC at their own minima; the ATC–AVC gap equals AFC.','MC 分别穿过 AVC 与 ATC 最低点。'),
make('g34-lratc',2,'3.3','scale','What does the falling segment of LRATC represent?',{curve:['Economies of scale','Diseconomies of scale','Increasing MC in the short run']},{curve:'Economies of scale'},'Along falling LRATC, larger long-run output reduces average total cost.','LRATC 向下倾斜表示规模经济。'),
make('g34-pc-axes',1,'3.7','competitive', 'Label a competitive firm’s per-unit revenue and cost diagram.',axes,{x:'Quantity',y:'Price / cost'},'The firm plots price, MR and per-unit costs against its own output.','企业以自身产量为横轴，单位收益和成本为纵轴。'),
make('g34-pc-curve',2,'3.7','competitive','Identify the horizontal blue line.',{curve:['P = MR = AR = firm demand','Market demand','ATC','Market supply']},{curve:'P = MR = AR = firm demand'},'A price taker receives the same price on each unit, so marginal and average revenue equal price.','价格接受者 P = MR = AR，企业需求水平。'),
make('g34-pc-build',4,'3.7','competitive','Complete the profit-maximizing competitive firm diagram.',{...axes,curves:['MC + ATC + AVC + P = MR','Demand + MR only'],label:['q* at rising MC = P','q* at minimum AVC'],outcome:['Profit because P > ATC at q*','Loss because MR = MC','Shutdown despite P > ATC']},{x:'Quantity',y:'Price / cost',curves:'MC + ATC + AVC + P = MR',label:'q* at rising MC = P',outcome:'Profit because P > ATC at q*'},'The higher intersection of P and MC selects output. The shaded rectangle is (P − ATC) × q*.','在上升 MC 与价格交点确定产量，利润面积为 (P−ATC)×q。'),
make('g34-monopoly-axes',1,'4.2','monopoly','Label the monopoly price-and-cost diagram.',axes,{x:'Quantity',y:'Price / cost'},'Price and per-unit cost are vertical, and output is horizontal.','纵轴价格与单位成本，横轴产量。'),
make('g34-monopoly-mr',2,'4.1','monopoly','Identify curve B, below the downward-sloping demand curve.',{curve:['MR','Demand','ATC','MC']},{curve:'MR'},'A single-price firm loses revenue on earlier units when it lowers price, so MR is below demand.','单一定价下 MR 在需求下方。'),
make('g34-monopoly-build',4,'4.2','monopoly','For D: P = 100 − Q and MC = 20, select the monopoly labels.',{...axes,curves:['D + MR + MC','D + Supply'],label:['Qm = 40; Pm = 60','Qm = 80; Pm = 20','Qm = 40; Pm = 20'],outcome:['DWL between Qm and Qe','Zero DWL at Qm','Price read from MR']},{x:'Quantity',y:'Price / cost',curves:'D + MR + MC',label:'Qm = 40; Pm = 60',outcome:'DWL between Qm and Qe'},'MR = 100 − 2Q gives Qm = 40. Demand gives Pm = 60. D = MC gives Qe = 80.','MR = MC 求 Qm，再从需求求 Pm；Qe 在 D = MC 处。'),
make('g34-discrimination',3,'4.3','discrimination','Move from single pricing to perfect price discrimination in the standard model.',{quantity:['Up to Qe = 80','Down to zero','Unchanged at 40'],outcome:['CS = 0; DWL = 0','CS increases; DWL increases','Producer surplus = 0']},{quantity:'Up to Qe = 80',outcome:'CS = 0; DWL = 0'},'Unit-specific prices capture willingness to pay. Output expands to D = MC and lost trades disappear.','逐单位按支付意愿收费，扩大到效率产量，CS 与 DWL 均为零。'),
make('g34-moncomp',4,'4.4','moncomp','Complete this long-run monopolistically competitive firm’s outcome.',{...axes,curves:['D + MR + MC + ATC','Horizontal D only'],label:['q* = 30; P = ATC = 50','q* at minimum ATC'],outcome:['Zero profit with excess capacity','Positive economic profit forever','P = MC and minimum ATC']},{x:'Quantity',y:'Price / cost',curves:'D + MR + MC + ATC',label:'q* = 30; P = ATC = 50',outcome:'Zero profit with excess capacity'},'At q = 30, MR = MC = 35 and demand is tangent to ATC at P = 50. Efficient scale is about 41.6, so excess capacity remains.','q=30 时 P=ATC=50，但 MC=35，且低于有效规模产量。'),
make('g34-game-nash',2,'4.5','game','Payoffs are (A, B). Identify the Nash equilibrium in this matrix.',{curve:['Low / Low','High / High','High / Low','Low / High']},{curve:'Low / Low'},'Low is a best response to either rival action for both players. At Low/Low a unilateral switch lowers payoff from 4 to 2.','双方 Low 为共同最优反应。'),
make('g34-game-incentive',3,'4.5','game','Give A a $3 bonus for choosing High, whatever B chooses. What is A’s new dominant strategy?',{curve:['High','Low','No dominant strategy'],outcome:['Nash: A High, B Low','Nash: A Low, B Low','Nash: A High, B High']},{curve:'High',outcome:'Nash: A High, B Low'},'A’s High payoffs become 11 and 5, exceeding Low’s 10 and 4. B still chooses Low.','A 的 High 收益变为 11 和 5，均高于 Low；B 仍选 Low。')
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function firmGraphSVG(model,config={}){
 if(!['costs','scale','competitive','monopoly','discrimination','moncomp','game','production','shutdown','competitive-loss'].includes(model))return null;
 const sx=q=>55+q*2.9,sy=p=>292-p*2.4;
 const text=(q,p,s,extra='')=>`<text x="${sx(q)}" y="${sy(p)}" ${extra}>${esc(s)}</text>`;
 const line=(q1,p1,q2,p2,color='#839693',dash='')=>`<path d="M${sx(q1)} ${sy(p1)}L${sx(q2)} ${sy(p2)}" fill="none" stroke="${color}" stroke-width="2" ${dash?`stroke-dasharray="${dash}"`:''}/>`;
 const curve=(fn,color,start=1,end=95)=>`<path d="${Array.from({length:191},(_,i)=>{const q=start+(end-start)*i/190;return `${i?'L':'M'}${sx(q)} ${sy(fn(q))}`;}).join(' ')}" fill="none" clip-path="url(#firm-plot)" stroke="${color}" stroke-width="2.6"/>`;
 const blue='#416b9b',green='#49796a',gold='#bc8732',red='#ad645b';let body='',name='',desc='';
 if(model==='game'){
  const bonus=config.curve==='High'&&config.outcome!==undefined;name='Two-firm payoff matrix';desc='Payoffs are A first, B second. Rows are A High and Low. Columns are B High and Low.';
  body=`<text x="20" y="28">Payoffs (A, B)${bonus?' · A High bonus: $3':''}</text><text x="210" y="62">Firm B</text><text x="155" y="93">High</text><text x="285" y="93">Low</text><text x="12" y="155">A High</text><text x="12" y="225">A Low</text><rect x="100" y="110" width="270" height="140" fill="#f4f7f4" stroke="#829693"/><path d="M235 110V250 M100 180H370" stroke="#829693"/><text x="145" y="152">(${bonus?'11':'8'}, 8)</text><text x="275" y="152">(${bonus?'5':'2'}, 10)</text><text x="145" y="222">(10, 2)</text><text x="275" y="222">(4, 4)</text><text x="20" y="295">Compare own payoff with rival’s action fixed.</text>`;
  return `<svg class="econ-graph" viewBox="0 0 400 350" role="img" aria-label="${name}"><title>${name}</title><desc>${desc}</desc>${body}</svg>`;
 }
 const hide=config.show===false;const buildEmpty=config.curves==='none';
 if(model==='production'){
  name='Total product of labor';desc='With capital fixed, TP first rises faster, then rises more slowly to the right of inflection point I.';
  body=curve(q=>.03*q*q-.0002*q*q*q,green,0,99)+text(88,94,'TP')+text(51,53,'I')+`<circle cx="${sx(50)}" cy="${sy(50)}" r="3" fill="${green}"/>`;
 }else if(model==='scale'){
  name='Long-run average total cost';desc='LRATC falls, reaches its minimum efficient scale, then rises.';
  body=curve(q=>18+.016*(q-52)**2,green)+text(73,38,'LRATC')+line(52,0,52,18,'#839693','4 4')+text(47,-8,'MES');
 }else if(['costs','competitive','shutdown','competitive-loss'].includes(model)){
  name=model==='costs'?'Short-run cost curves':'Competitive firm with economic profit';desc='ATC lies above AVC. MC intersects each average at its minimum.';
  const avc=q=>40-.8*q+.006*q*q,mc=q=>40-1.6*q+.018*q*q,atc=q=>avc(q)+400/q;
  body=curve(atc,blue,6)+curve(avc,green)+curve(mc,red)+text(86,51,'MC')+text(85,28,config.identify?'A':'ATC')+text(90,18,'AVC');
  if(model==='costs'&&config.direction){const delta=config.direction==='Up'?200:-200;const fn=config.curve==='ATC'?q=>atc(q)+delta/q:config.curve==='AVC'?q=>avc(q)+delta/20:q=>mc(q)+delta/20;body+=curve(fn,gold,7)+text(38,43,'Selected change');}
  if(['competitive','competitive-loss','shutdown'].includes(model)){
   const p=model==='shutdown'?8:model==='competitive-loss'?16:30,q=(1.6+Math.sqrt(2.56-.072*(40-p)))/.036,a=atc(q);
   body=`<rect x="${sx(0)}" y="${sy(Math.max(p,a))}" width="${sx(q)-sx(0)}" height="${Math.abs(sy(a)-sy(p))}" fill="#49796a" opacity=".12"/>`+body+line(0,p,99,p,blue)+text(8,34,'P = MR = AR')+line(q,0,q,p,'#839693','4 4')+text(q-5,-8,'q*')+text(2,p+1,String(p));
   if(model==='shutdown'){body=curve(atc,blue,6)+curve(avc,green)+curve(mc,red)+line(0,p,99,p,blue)+text(8,p+4,'P = 8 < min AVC')+text(86,51,'MC')+text(85,28,'ATC')+text(90,18,'AVC');name='Competitive firm shutdown';desc='The price line lies below minimum AVC, so the firm produces zero.';}
   if(model==='competitive-loss'){name='Competitive firm with a short-run loss';desc='At chosen output AVC is below price, which is below ATC. The shaded rectangle is a loss.';}
  }
 }else if(model==='moncomp'){
  name='Long-run monopolistic competition';desc='Demand is tangent to ATC at q 30 and price 50. MR equals MC at 35. Minimum ATC occurs near q 41.6.';
  body=curve(monopolisticCompetitionModel.demand,blue)+curve(monopolisticCompetitionModel.mr,red,0,65)+curve(monopolisticCompetitionModel.mc,green,0,65)+curve(monopolisticCompetitionModel.atc,gold,10,95)+text(81,28,'D')+text(57,11,'MR')+text(61,84,'MC')+text(79,64,'ATC')+line(30,0,30,50,'#839693','4 4')+line(0,50,30,50,'#839693','4 4')+text(23,-8,'q* = 30')+text(0,53,'P = 50');
 }else{
  const perfect=model==='discrimination'&&config.quantity==='Up to Qe = 80';name=perfect?'Perfect price discrimination':'Single-price monopoly';desc='Demand P = 100 − Q, MR = 100 − 2Q, MC = 20. Single-price Qm 40 and Pm 60; efficient Qe 80.';
  body=perfect?`<polygon points="${sx(0)},${sy(100)} ${sx(0)},${sy(20)} ${sx(80)},${sy(20)}" fill="${green}" opacity=".16"/>`:`<polygon points="${sx(40)},${sy(60)} ${sx(40)},${sy(20)} ${sx(80)},${sy(20)}" fill="${gold}" opacity=".22"/>`;
  body+=line(0,100,100,0,blue)+line(0,20,100,20,green)+text(89,12,perfect?'D = MR':'D')+text(92,24,'MC');
  if(!perfect)body+=line(0,100,50,0,red)+text(43,8,config.identify?'B':'MR')+line(40,0,40,60,'#839693','4 4')+line(0,60,40,60,'#839693','4 4')+text(33,-8,'Qm')+text(1,63,'Pm = 60')+text(49,32,'DWL');
  body+=line(80,0,80,20,'#839693','4 4')+text(75,-8,'Qe');
 }
 if(buildEmpty)body='';
 return `<svg class="econ-graph" viewBox="0 0 400 350" role="img" aria-label="${name}"><title>${name}</title><desc>${desc}</desc><defs><clipPath id="firm-plot"><rect x="55" y="30" width="300" height="264"/></clipPath></defs><path d="M55 30V292H365" fill="none" stroke="#829693"/><text x="12" y="22">${esc(config.y||(hide?'?':model==='production'?'Output':'Price / cost'))}</text><text x="280" y="337">${esc(config.x||(hide?'?':model==='production'?'Labor':'Quantity'))}</text><g style="font-size:12px">${body}</g></svg>`;
}
