// Original learning material aligned to the user-supplied AP Macroeconomics CED.
const rows=[];
const add=(id,title,zh,summary,points,example,mistake,terms,checks)=>rows.push({id,title,zh,summary,points:points.split('|'),example,mistake,terms,checks});
add('1.1','Scarcity','稀缺性','Limited resources require choices.',
'Scarcity exists when wants exceed available resources.|Land, labor, physical capital and entrepreneurship are productive resources.|Choosing one use of a resource gives up its next-best alternative.',
'A town has one available site. Building a library means giving up the best alternative use, perhaps a clinic.','Scarcity is not the same as a temporary market shortage.',
'Scarcity~Limited resources relative to wants.~稀缺性|Economic resource~An input used to produce goods and services.~经济资源|Opportunity cost~The value of the next-best alternative forgone.~机会成本',
[['A wealthy country still faces scarcity because:','Resources remain limited relative to wants.','It must have a shortage of currency.','Every market has excess demand.','Its government cannot make choices.','More wealth does not eliminate limited time, land and other resources.','财富增加也不能消除资源限制。'],['A student studies economics instead of taking the best available paid shift. The opportunity cost is:','The value of the forgone shift.','All possible jobs combined.','The tuition already paid only.','Zero because studying is useful.','Opportunity cost concerns the next-best alternative sacrificed.','机会成本是放弃的最佳替代选择。']]);
add('1.2','Opportunity Cost and the Production Possibilities Curve (PPC)','机会成本与生产可能性曲线','A PPC shows feasible production combinations and trade-offs.',
'Points on the PPC are productively efficient; points inside show underused resources.|Points outside are currently unattainable with existing resources and technology.|A straight PPC has constant opportunity cost; a bowed-out PPC has increasing opportunity cost.|More resources or improved technology can shift the PPC outward.',
'Moving from 10 food and 0 machines to 8 food and 1 machine costs 2 units of food per machine.','Moving toward an existing PPC uses idle resources; it does not necessarily increase productive capacity.',
'PPC~A boundary of maximum feasible combinations of two outputs.~生产可能性曲线|Productive efficiency~Producing on the production possibilities frontier.~生产效率|Economic growth~An increase in sustainable productive capacity.~经济增长',
[['A factory employs previously idle workers with unchanged technology. Its production moves:','From inside toward the existing PPC.','To a necessarily outward-shifted PPC.','Beyond all feasible combinations.','Along an inward-shifting PPC.','Using idle inputs raises utilization without necessarily changing capacity.','利用闲置资源不等于扩大生产能力。'],['One more computer requires giving up 4 meals. Its opportunity cost is:','4 meals.','One fourth of a meal.','5 meals.','Zero meals.','Opportunity cost is the output sacrificed per additional unit obtained.','每增加一台电脑需放弃四餐。']]);
add('1.3','Comparative Advantage and Gains from Trade','比较优势与贸易收益','Specialize according to relative opportunity costs.',
'Absolute advantage means producing more with the same resources.|Comparative advantage means producing at a lower opportunity cost.|Mutually beneficial terms of trade lie between the producers’ opportunity costs.|Trade can permit consumption beyond a country’s own PPC.',
'A can make 10 wheat or 5 cloth; B can make 6 wheat or 6 cloth. Cloth costs A 2 wheat and B 1 wheat. B specializes in cloth; 1 cloth for 1.5 wheat benefits both.','Absolute advantage in both goods does not eliminate gains from comparative advantage.',
'Absolute advantage~Higher output from the same resources.~绝对优势|Comparative advantage~A lower opportunity cost of production.~比较优势|Terms of trade~The exchange ratio between traded goods.~贸易条件',
[['Cloth costs A 2 wheat and B 1 wheat. Who has comparative advantage in cloth?','B.','A.','Both have identical costs.','Neither can trade.','B sacrifices less wheat per cloth.','B生产布的机会成本较低。'],['Which exchange rate benefits both in that example?','1 cloth for 1.5 wheat.','1 cloth for 3 wheat.','1 cloth for 0.5 wheat.','No rate can benefit both.','The rate lies strictly between 1 and 2 wheat per cloth.','互利交换比率在双方机会成本之间。']]);
add('1.4','Demand','需求','Separate a price movement from a change in buying conditions.',
'Quantity demanded falls as own price rises, other things equal.|A change in own price is a movement along demand.|Income, tastes, related-good prices, expectations and the number of buyers shift demand.|For a normal good, higher income increases demand; for an inferior good it reduces demand.',
'If tea becomes more expensive, consumers may demand more coffee, a substitute. Coffee demand shifts right even before coffee’s price changes.','Demand and quantity demanded are different concepts.',
'Demand~Quantities buyers are willing and able to buy at different prices.~需求|Substitute~A good that can replace another in consumption.~替代品|Normal good~A good whose demand rises when income rises.~正常品',
[['The price of coffee itself falls. Other things equal, this causes:','A movement along coffee demand.','A rightward shift of coffee demand.','A leftward shift of coffee demand.','No change in quantity demanded.','Own-price changes move along a given demand curve.','自身价格变化引起沿曲线移动。'],['Income rises and demand for bus rides falls. Bus rides are, in this example:','An inferior good.','A normal good.','A production input.','Necessarily a public good.','Inferior-good demand falls as income rises.','劣等品需求随收入增加而减少。']]);
add('1.5','Supply','供给','Production conditions determine how much firms offer at each price.',
'A higher own price generally increases quantity supplied.|Input costs, technology, taxes, subsidies and seller numbers can shift supply.|Lower unit production costs shift supply right.|Distinguish a supply shift from movement along supply.',
'Cheaper fertilizer lowers farm costs and shifts wheat supply right; the market price may then fall.','A lower selling price alone does not shift supply left.',
'Supply~Quantities sellers offer at different prices.~供给|Input cost~The expense of resources used in production.~投入成本|Quantity supplied~The amount offered at a particular price.~供给量',
[['A technological improvement lowers unit costs. Supply usually:','Shifts right.','Shifts left.','Moves along an unchanged curve only.','Becomes demand.','Lower costs make more production worthwhile at each price.','成本下降使各价格下供给增加。'],['A rise in the good’s own price, other things equal, causes:','An increase in quantity supplied.','A decrease in supply.','An increase in supply.','A fall in quantity supplied.','This is movement along the supply curve.','这是沿供给曲线的移动。']]);
add('1.6','Market Equilibrium, Disequilibrium, and Changes in Equilibrium','市场均衡与变化','Prices adjust when planned purchases and sales differ.',
'Equilibrium occurs where quantity demanded equals quantity supplied.|A shortage creates upward pressure on price; a surplus creates downward pressure.|Higher demand raises equilibrium price and quantity with supply unchanged.|If both curves shift, one outcome may be ambiguous without relative shift sizes.',
'At a price of $4, buyers want 80 units and sellers offer 50. The shortage is 30 units.','With demand and supply both increasing, quantity rises but the price change is ambiguous.',
'Equilibrium~A situation in which quantity demanded equals quantity supplied.~均衡|Shortage~Quantity demanded exceeds quantity supplied at the current price.~短缺|Surplus~Quantity supplied exceeds quantity demanded at the current price.~过剩',
[['At a price, Qd is 80 and Qs is 50. The market has:','A shortage of 30.','A surplus of 30.','A shortage of 130.','An equilibrium of 50.','Shortage equals Qd minus Qs at the given price.','短缺量为80减50。'],['Both demand and supply increase. Which result is certain in the standard model?','Equilibrium quantity increases.','Equilibrium price increases.','Equilibrium price decreases.','Equilibrium quantity decreases.','Both shifts raise quantity, but they push price in opposite directions.','数量效应同向，价格效应相反。']]);
add('2.1','The Circular Flow and GDP','循环流动与国内生产总值','Final spending, income and value added measure the same production.',
'GDP measures final goods and services produced within an economy during a period.|Expenditure GDP equals C + I + G + exports − imports.|Income and value-added approaches avoid counting the same production twice.|Transfers, financial asset trades and used goods are not new final production.',
'C = 600, I = 150, G = 200, X = 80 and M = 100 give GDP = 930.','Purchasing stocks is financial investment, not the investment component of GDP.',
'GDP~The value of final domestic production during a period.~国内生产总值|Value added~A producer’s sales value minus purchased intermediate inputs.~增加值|Net exports~Exports minus imports.~净出口',
[['C=600, I=150, G=200, X=80, M=100. GDP equals:','930.','1130.','1030.','750.','600 + 150 + 200 + 80 − 100 = 930.','支出法加出口、减进口。'],['Which is included in current GDP?','A newly produced machine bought by a firm.','A purchase of existing company shares.','An unemployment benefit payment itself.','The full resale value of a used car.','New capital equipment is current investment spending.','新生产的资本设备计入投资。']]);
add('2.2','Limitations of GDP','GDP的局限','Measured production is not a complete measure of well-being.',
'GDP omits many unpaid household and nonmarket activities.|GDP does not describe income distribution.|Environmental quality, leisure and other quality-of-life factors are not directly measured.|Real GDP per capita is useful but incomplete as a living-standard indicator.',
'Paying for childcare increases measured GDP, while otherwise identical unpaid care at home is generally uncounted.','A rise in GDP does not prove that everyone is better off.',
'Nonmarket production~Production not exchanged through recorded markets.~非市场生产|Living standard~Material conditions of life, only partly captured by GDP.~生活水平|Income distribution~How total income is divided among people.~收入分配',
[['Which activity is generally omitted from measured GDP?','Unpaid childcare by a parent.','Paid childcare at a business.','New construction.','A restaurant meal.','Unpaid household services are generally outside measured market production.','无偿家庭服务通常未计入。'],['Higher GDP alone establishes that:','Measured output value has increased.','Income inequality has fallen.','Pollution has fallen.','Every household is richer.','GDP measures production, not each aspect of welfare or distribution.','GDP不是完整福利或分配指标。']]);
add('2.3','Unemployment','失业','Labor-force status determines the unemployment rate.',
'The labor force includes employed people and unemployed people actively seeking work.|Unemployment rate = unemployed / labor force × 100.|Participation rate = labor force / adult population × 100.|Natural unemployment consists of frictional and structural unemployment; cyclical unemployment reflects the output gap.|Discouraged workers are outside the labor force; involuntary part-time workers count as employed.',
'With 90 employed, 10 unemployed and 25 outside the labor force, unemployment is 10% and participation is 80%.','Full employment does not mean zero unemployment.',
'Frictional unemployment~Joblessness during search or transitions between jobs.~摩擦性失业|Structural unemployment~Joblessness caused by a mismatch of skills or location.~结构性失业|Cyclical unemployment~Unemployment associated with departures from full-employment output.~周期性失业',
[['There are 90 employed and 10 unemployed people. The unemployment rate is:','10%.','11.1%.','90%.','8%.','The denominator is the labor force: 90 + 10 = 100.','分母为劳动力总数。'],['A job seeker stops looking because no jobs seem available. Initially, the person becomes:','Outside the labor force.','Employed full time.','Structurally employed.','Still counted as actively searching.','Discouraged workers are not included in the labor force.','丧失信心且停止求职者不计入劳动力。']]);
add('2.4','Price Indices and Inflation','价格指数与通货膨胀','Price indices separate money values from purchasing power.',
'CPI = current fixed-basket cost / base-year basket cost × 100.|Inflation is the percentage change in a price index.|Deflation is a falling price level; disinflation is slower positive inflation.|Real value = nominal value / price index × 100.|A fixed basket can overstate living-cost increases through substitution bias; PPI calculation is excluded from this syllabus.',
'A basket rises from $200 to $240: CPI = 120. If last year’s CPI was 110, inflation is 9.09%, not 10%.','A fall in the inflation rate does not necessarily mean prices fall.',
'Inflation~An increase in the overall price level.~通货膨胀|Disinflation~A decline in the rate of inflation.~通胀放缓|CPI~The cost of a fixed consumer basket relative to its base-year cost.~消费者价格指数',
[['CPI rises from 120 to 126. Inflation is:','5%.','6%.','26%.','20%.','(126 − 120) / 120 × 100 = 5%.','用上一期指数作为分母。'],['Inflation falls from 6% to 2%. This is:','Disinflation; prices still rise.','Deflation; prices fall 4%.','Zero inflation.','A 4% increase in real GDP.','A smaller positive inflation rate still means a rising price level.','通胀率下降不等于物价下降。']]);
add('2.5','Costs of Inflation','通货膨胀的成本','Unexpected inflation changes the real value of fixed nominal contracts.',
'Expected inflation can be incorporated into nominal contracts.|Unexpected inflation reduces the real burden of fixed nominal debt.|Borrowers can gain while lenders lose when inflation exceeds expectations.|Unexpected deflation reverses this redistribution; fixed nominal incomes lose purchasing power when prices rise.',
'A fixed loan charges 5%. Inflation was expected to be 2% but is 4%; the realized real rate is about 1%, below the expected 3%.','Distinguish unexpected inflation from inflation already built into a contract.',
'Unexpected inflation~Inflation different from the rate anticipated in decisions.~未预期通胀|Purchasing power~The goods and services a sum of money can buy.~购买力|Fixed nominal income~Income whose money amount does not adjust with prices.~固定名义收入',
[['Inflation exceeds expectations on a fixed-rate loan. Who generally benefits?','The borrower.','The lender.','Both necessarily gain equally.','Neither is affected in real terms.','The borrower repays money with lower purchasing power than expected.','实际偿债负担下降。'],['Unexpected deflation generally makes fixed nominal debt:','More burdensome in real terms.','Less burdensome in real terms.','Disappear.','Automatically pay a lower nominal rate.','Falling prices increase the purchasing power of the fixed repayment.','固定还款的实际价值上升。']]);
add('2.6','Real v. Nominal GDP','实际与名义GDP','Real GDP removes the effect of price changes.',
'Nominal GDP uses current prices and current quantities.|Real GDP uses constant prices to measure output.|GDP deflator = nominal GDP / real GDP × 100.|A nominal increase can reflect more output, higher prices or both.',
'Nominal GDP of 1200 with a deflator of 120 implies real GDP of 1000.','Do not compare nominal output across years as if all changes were real growth.',
'Nominal GDP~Current output valued at current prices.~名义GDP|Real GDP~Output valued using constant prices.~实际GDP|GDP deflator~A price index equal to nominal GDP divided by real GDP times 100.~GDP平减指数',
[['Nominal GDP is 1200 and the deflator is 120. Real GDP is:','1000.','1440.','1080.','10.','1200 / 120 × 100 = 1000.','名义GDP除以指数再乘100。'],['Quantities are unchanged but all prices double. What happens?','Nominal GDP doubles; real GDP is unchanged.','Both measures double.','Real GDP doubles only.','Both measures fall.','Real GDP holds prices constant.','实际GDP剔除价格变化。']]);
add('2.7','Business Cycles','经济周期','Actual output fluctuates around potential output.',
'Expansion and recession are phases; peaks and troughs are turning points.|Potential output is sustainable full-employment output.|A negative output gap occurs when actual output is below potential.|Employment generally rises with real output; cyclical unemployment rises in recessions.',
'Actual GDP of 950 against potential GDP of 1000 gives a gap of −50, or −5% of potential.','A recession is not the same as a permanent fall in productive capacity.',
'Expansion~A phase of rising aggregate output and employment.~扩张|Recession~A phase of declining aggregate output.~衰退|Output gap~Actual output minus potential output.~产出缺口',
[['Actual GDP is below potential GDP. The economy has:','A recessionary gap.','An inflationary gap.','No cyclical unemployment by definition.','A necessarily smaller labor force.','Output below potential is a negative or recessionary gap.','实际产出低于潜在产出。'],['The turning point from recession to expansion is a:','Trough.','Peak.','Price index.','Budget deficit.','A trough marks the low turning point in the business cycle.','谷底是从衰退转向扩张的拐点。']]);
add('3.1','Aggregate Demand (AD)','总需求','AD relates the price level to total planned spending on real output.',
'AD includes consumption, investment, government purchases and net exports.|The real wealth, interest rate and exchange rate effects explain its downward slope.|Price-level changes cause movement along AD.|Independent changes in C, I, G or NX shift AD.',
'Greater business confidence raises investment at each price level, shifting AD right.','The AD curve is not a single-good demand curve.',
'Aggregate demand~Total real output demanded at each price level.~总需求|Wealth effect~A lower price level raises the purchasing power of nominal wealth.~财富效应|Investment spending~Spending on newly produced capital and inventories.~投资支出',
[['Higher business confidence increases investment. AD:','Shifts right.','Shifts left.','Moves along an unchanged curve only.','Becomes vertical.','Investment is a component of aggregate demand.','投资增加使总需求右移。'],['A fall in the price level, other things equal, causes:','Movement along AD toward greater real output demanded.','A leftward AD shift.','A rightward AD shift by definition.','A fall in potential output.','The price level is on the axis, so its change is a movement along AD.','物价水平变化对应沿AD移动。']]);
add('3.2','Multipliers','乘数','One spending change can generate several rounds of income and spending.',
'MPC = change in consumption / change in disposable income.|MPC + MPS = 1.|The simple expenditure multiplier is 1 / (1 − MPC).|The simple tax multiplier is −MPC / (1 − MPC).|These calculations hold other leakages and price-level feedback aside.',
'With MPC 0.8, the spending multiplier is 5 and the tax multiplier is −4. A $10 spending increase implies $50 more output in the simple model.','A tax cut first changes disposable income; not every dollar is spent.',
'MPC~The fraction of additional disposable income consumed.~边际消费倾向|MPS~The fraction of additional disposable income saved.~边际储蓄倾向|Expenditure multiplier~The change in output per autonomous spending change in the simple model.~支出乘数',
[['MPC is 0.75. The simple spending multiplier equals:','4.','0.25.','3.','0.75.','1 / (1 − 0.75) = 4.','支出乘数为储蓄倾向的倒数。'],['MPC is 0.75 and taxes rise by 20. The simple output change is:','−60.','+60.','−80.','+20.','The tax multiplier is −3; −3 × 20 = −60.','税收乘数带负号。']]);
add('3.3','Short-Run Aggregate Supply (SRAS)','短期总供给','Sticky input prices allow output to respond to the price level.',
'SRAS relates real output supplied to the price level.|Sticky wages and prices help explain its upward slope.|Higher nominal input costs shift SRAS left.|Higher productivity shifts SRAS right.|Along SRAS, greater output normally means more employment.',
'An oil-price shock raises costs and shifts SRAS left, raising prices while reducing output.','An input-price shock shifts SRAS; a change in the overall price level moves along it.',
'SRAS~Real output supplied at each price level in the short run.~短期总供给|Sticky wages~Nominal wages that adjust slowly.~工资黏性|Supply shock~A change in production conditions affecting aggregate supply.~供给冲击',
[['A rise in nominal wages with productivity unchanged shifts SRAS:','Left.','Right.','Neither direction.','Into AD.','Higher unit labor costs reduce supply at each price level.','单位劳动成本上升使SRAS左移。'],['Along an upward-sloping SRAS curve, greater output is associated with:','A higher price level and more employment.','A lower price level and less employment.','Unchanged employment necessarily.','A lower potential output necessarily.','With sticky inputs, higher output and prices move together in the short run.','短期沿SRAS移动时产出与物价同向。']]);
add('3.4','Long-Run Aggregate Supply (LRAS)','长期总供给','Potential output depends on resources and productivity.',
'In the long run, wages and prices can fully adjust.|LRAS is vertical at full-employment output.|A higher price level alone does not increase sustainable capacity.|The PPC and LRAS both describe productive capacity.',
'If prices and nominal wages both double with resources unchanged, firms have no lasting reason to double real production.','Full-employment output can coexist with frictional and structural unemployment.',
'LRAS~A vertical curve at sustainable full-employment output.~长期总供给|Potential output~Sustainable output when unemployment is at its natural rate.~潜在产出|Long run~A period in which wages and prices can fully adjust.~长期',
[['LRAS is vertical because in the long run:','Wages and prices adjust while real capacity determines output.','All unemployment is zero.','Demand never changes.','The price level is fixed.','Real resources and productivity determine potential output.','长期产出由实际生产能力决定。'],['Which change can shift LRAS right?','An increase in productive technology.','A higher price level alone.','A temporary rise in consumption alone.','A higher nominal wage with no productivity change.','Technology raises sustainable capacity.','技术进步提高潜在产出。']]);
add('3.5','Equilibrium in the Aggregate Demand–Aggregate Supply (AD–AS) Model','AD–AS模型中的均衡','Compare current equilibrium output with potential output.',
'Short-run equilibrium is the intersection of AD and SRAS.|Long-run equilibrium additionally lies on LRAS.|Output below potential is a recessionary gap.|Output above potential is an inflationary gap.',
'If AD meets SRAS at 900 while LRAS is at 1000, the economy has a recessionary gap of 100.','Short-run equilibrium need not occur at full employment.',
'Short-run equilibrium~An intersection where aggregate output demanded equals supplied.~短期均衡|Recessionary gap~Actual output below potential output.~衰退缺口|Inflationary gap~Actual output above potential output.~通胀缺口',
[['AD and SRAS intersect to the left of LRAS. This indicates:','A recessionary gap.','An inflationary gap.','Long-run equilibrium.','Zero unemployment.','Actual output is below potential.','均衡产出低于潜在产出。'],['Long-run macroeconomic equilibrium requires:','AD and SRAS to intersect on LRAS.','AD to be vertical.','The price level to equal zero.','Unemployment to equal zero.','All three curves meet at potential output.','三条曲线交于充分就业产出。']]);
add('3.6','Changes in the AD–AS Model in the Short Run','AD–AS模型的短期变化','Demand and supply shocks produce different price-output patterns.',
'An AD increase raises output and prices in the short run.|An AD decrease reduces output and prices.|A favorable SRAS shift raises output and lowers prices.|An adverse SRAS shift lowers output and raises prices, creating stagflation.',
'Falling consumer confidence shifts AD left: output and employment fall and the price level falls, other things equal.','An increase in inflation with falling output points to an adverse supply shock, not a positive demand shock.',
'Demand-pull inflation~Rising prices associated with stronger aggregate demand.~需求拉动型通胀|Cost-push inflation~Rising prices associated with higher production costs.~成本推动型通胀|Stagflation~Rising prices together with weak output and higher unemployment.~滞胀',
[['An adverse aggregate supply shock causes:','Higher prices and lower output.','Higher prices and higher output.','Lower prices and higher output.','Lower prices and lower output.','SRAS shifts left, producing stagflation.','SRAS左移造成滞胀。'],['A positive AD shock in the short run generally causes unemployment to:','Fall as output rises.','Rise as output rises.','Remain at zero.','Equal the inflation rate.','Higher output normally requires greater employment.','产出增加通常提高就业。']]);
add('3.7','Long-Run Self-Adjustment','长期自我调整','Wage and price adjustment can close temporary output gaps.',
'In a recessionary gap, downward wage adjustment can shift SRAS right.|In an inflationary gap, rising wages can shift SRAS left.|With capacity unchanged, adjustment returns output to LRAS.|Economic growth is different: it changes LRAS itself.',
'After an AD decline, lower wages eventually reduce production costs; output returns to potential at a lower price level.','The direction of wage adjustment depends on whether output is above or below potential.',
'Self-adjustment~Wage and price changes that restore full-employment equilibrium.~自我调整|Nominal wage~A wage expressed in money units.~名义工资|Natural unemployment rate~Frictional plus structural unemployment at full employment.~自然失业率',
[['Without policy, a recessionary gap tends to close as:','Nominal wages fall and SRAS shifts right.','Nominal wages rise and SRAS shifts left.','LRAS always shifts left.','AD necessarily shifts right by law.','Lower costs allow more output at each price level.','工资下降使生产成本下降。'],['After a temporary AD increase, long-run adjustment with unchanged capacity restores:','Potential output at a higher price level.','Permanently higher real output.','Zero inflation and zero unemployment.','A larger PPC necessarily.','Wages adjust; AD alone does not expand productive capacity.','总需求增加本身不扩大长期生产能力。']]);
add('3.8','Fiscal Policy','财政政策','Government spending and taxes influence aggregate demand.',
'Expansionary policy raises government purchases or lowers taxes to support demand.|Contractionary policy lowers purchases or raises taxes to restrain demand.|Purchases affect AD directly; taxes and transfers work through disposable income.|Use simple multipliers to calculate policy changes, while recognizing price and crowding-out effects.|Discretionary fiscal policy faces decision and implementation lags.',
'With MPC 0.8, a simple recessionary gap of 100 can be closed by 20 more purchases or a 25 tax cut, before other offsets.','The tax multiplier is negative and smaller in absolute value than the spending multiplier.',
'Fiscal policy~Changes in government purchases, taxes or transfers to influence the economy.~财政政策|Expansionary fiscal policy~Fiscal action intended to increase aggregate demand.~扩张性财政政策|Policy lag~A delay between a problem, policy action and its effects.~政策时滞',
[['Which policy is expansionary?','An increase in government purchases.','A decrease in government purchases.','A tax increase with spending unchanged.','A reduction in transfers with taxes unchanged.','Higher purchases directly raise aggregate demand.','政府购买增加直接提高AD。'],['MPC=0.8. In the simple model, a gap of 100 requires a spending increase of:','20.','25.','80.','100.','The multiplier is 5; 100 / 5 = 20.','先求乘数，再用缺口除以乘数。']]);
add('3.9','Automatic Stabilizers','自动稳定器','Existing tax and transfer rules cushion business cycles.',
'Automatic stabilizers operate without new legislation.|Tax revenue tends to fall when income falls, cushioning disposable income.|Eligible transfers often rise in a recession.|During expansion, higher taxes and lower eligible transfers restrain demand growth.',
'When a worker loses a job, eligible unemployment benefits support consumption under an existing program.','Automatic stabilizers moderate a downturn; they do not guarantee that it disappears.',
'Automatic stabilizer~An existing rule that moderates fluctuations without a new policy decision.~自动稳定器|Transfer payment~A government payment not exchanged for current goods or services.~转移支付|Disposable income~Income available after taxes and including relevant transfers.~可支配收入',
[['Which is an automatic stabilizer?','Tax payments fall as income falls under existing rules.','A newly legislated infrastructure program.','A new central-bank bond purchase.','A new tax law passed after a recession starts.','The existing rule responds without a new discretionary decision.','既有制度自动响应经济变化。'],['During a recession, automatic stabilizers usually:','Support disposable income and consumption.','Eliminate every output gap immediately.','Raise taxes to reduce consumption.','Require a new law for every benefit payment.','They soften, rather than necessarily eliminate, the decline.','自动稳定器缓和但不必然消除衰退。']]);
add('4.1','Financial Assets','金融资产','Compare liquidity, risk and return before choosing an asset.',
'Cash and demand deposits are highly liquid.|Bonds represent debt; stocks represent equity ownership.|Existing fixed-payment bond prices and market interest rates move inversely.|Forgone interest is an opportunity cost of holding non-interest-bearing money.',
'A bond pays $50 annually. At a price of $1000 its current yield is 5%; at $800 it is 6.25%.','A bond’s fixed payment need not change when its market price changes.',
'Liquidity~How readily an asset can be used for payment without substantial loss.~流动性|Bond~A debt asset promising specified payments.~债券|Stock~An ownership share in a corporation.~股票',
[['Market interest rates rise. An existing fixed-payment bond’s price tends to:','Fall.','Rise.','Stay fixed by definition.','Become its face value automatically.','Its fixed payments become less attractive than new higher-yield alternatives.','新债券收益提高使旧债券价格下降。'],['The opportunity cost of holding non-interest-bearing cash is:','The return forgone on an alternative asset.','Always zero.','The entire money supply.','The bond’s face value only.','Cash provides liquidity but sacrifices potential interest income.','持币会放弃其他资产收益。']]);
add('4.2','Nominal v. Real Interest Rates','名义与实际利率','Inflation changes the purchasing power of interest payments.',
'The nominal rate is the stated money interest rate.|Expected nominal rate ≈ expected real rate + expected inflation.|Realized real rate ≈ nominal rate − actual inflation.|Expected and realized real returns differ when inflation surprises occur.',
'A loan charges 7%; expected inflation is 3%, so the expected real rate is about 4%. Actual inflation of 5% makes the realized real rate about 2%.','Use expected inflation for contract expectations and actual inflation for realized returns.',
'Nominal interest rate~The stated interest rate before adjustment for inflation.~名义利率|Real interest rate~The interest rate adjusted for inflation.~实际利率|Expected inflation~The inflation rate anticipated when making a decision.~预期通胀',
[['Nominal interest is 8% and actual inflation is 3%. The approximate real rate is:','5%.','11%.','3%.','24%.','8 − 3 = 5 percentage points.','实际利率约等于名义利率减通胀率。'],['Expected real return is 2% and expected inflation is 4%. The approximate nominal rate is:','6%.','2%.','−2%.','8%.','The nominal rate incorporates both expected real return and inflation.','名义利率包含实际回报和通胀补偿。']]);
add('4.3','Definition, Measurement, and Functions of Money','货币的定义、衡量与职能','Money enables exchange and records value.',
'Money serves as a medium of exchange, unit of account and store of value.|M1 and M2 are monetary aggregates; classify components using the definition supplied in a question.|The monetary base equals currency in circulation plus bank reserves.|Bank reserves belong to the base but are not household spending balances.',
'Currency in circulation of 200 and bank reserves of 100 give a monetary base of 300.','Do not add M1 to M2: M2 already includes M1. Monetary classifications can change over time.',
'Medium of exchange~An asset accepted in payment for goods and services.~交换媒介|Unit of account~A common measure for quoting prices and debts.~计价单位|Monetary base~Currency in circulation plus bank reserves.~货币基础',
[['Currency in circulation is 200 and reserves are 100. The monetary base equals:','300.','200.','100.','20000.','Add currency and bank reserves.','货币基础为流通现金加银行准备金。'],['Listing every price in dollars illustrates money as a:','Unit of account.','Production machine.','Fiscal multiplier.','Reserve requirement.','A common price denomination is the unit-of-account function.','统一报价体现计价单位职能。']]);
add('4.4','Banking and the Expansion of the Money Supply','银行与货币供给扩张','Bank lending can create deposits within balance-sheet constraints.',
'Bank assets include reserves and loans; deposits are liabilities.|Required reserves equal the reserve ratio times reservable deposits.|Excess reserves equal total reserves minus required reserves.|In the simple limited-reserves model, the maximum multiplier is 1 / reserve ratio.|Cash leakage and banks holding excess reserves reduce expansion; distinguish a cash deposit from newly created reserves.',
'A bank has deposits of 1000 and reserves of 150 with a 10% requirement. Required reserves are 100 and excess reserves are 50.','A customer depositing existing currency changes the form of money; it does not initially create the same amount of new money.',
'Required reserves~Reserves a bank must hold under a specified requirement.~法定准备金|Excess reserves~Reserves above the required amount.~超额准备金|Simple money multiplier~The maximum deposit expansion factor, 1 divided by the reserve ratio, under restrictive assumptions.~简单货币乘数',
[['Deposits are 1000, reserves 150 and the required ratio 10%. Excess reserves equal:','50.','100.','150.','900.','Required reserves are 100, leaving 50 excess.','150减100等于50。'],['In the simple model with a 20% reserve requirement, the maximum multiplier is:','5.','20.','0.2.','4.','1 / 0.20 = 5, assuming no leakage or extra reserve holding.','简单乘数为法定准备金率的倒数。']]);
add('4.5','The Money Market','货币市场','The basic money market determines a nominal interest rate.',
'Money demand slopes down because higher interest increases the opportunity cost of holding money.|The basic model draws money supply vertically.|Equilibrium occurs where money demand equals money supply.|Higher price levels or real income increase transaction demand for money.|In the limited-reserves model, greater money supply lowers the equilibrium nominal rate.',
'With supply fixed, higher nominal spending raises money demand and the equilibrium nominal interest rate.','The money-market vertical axis is a nominal rate; the loanable-funds model normally uses a real rate.',
'Money demand~Desired holdings of money at each nominal interest rate.~货币需求|Money supply~The stock of money available in an economy.~货币供给|Money-market equilibrium~Equality of money demanded and supplied at a nominal interest rate.~货币市场均衡',
[['With money supply fixed, greater money demand makes the nominal interest rate:','Rise.','Fall.','Become zero.','Equal the reserve ratio.','The demand shift raises the intersection with vertical money supply.','需求右移使均衡名义利率上升。'],['Money demand slopes down because a higher nominal interest rate:','Raises the opportunity cost of holding money.','Makes cash earn more interest automatically.','Reduces all prices to zero.','Eliminates the need for transactions.','Alternative interest-bearing assets become more attractive.','利率提高使持有现金的机会成本上升。']]);
add('4.6','Monetary Policy','货币政策','Policy implementation depends on the reserve regime.',
'Central banks use policy to influence interest rates and macroeconomic conditions.|Open-market purchases increase reserves and the monetary base; sales reduce them.|In limited reserves, reserve changes can influence rates and multiplied deposits.|In ample reserves, changing reserve supply alone may not effectively move rates; administered interest rates are central tools.|Lower rates can stimulate interest-sensitive spending and AD; higher rates can restrain them.|Recognition and transmission lags delay policy effects.',
'With ample reserves, lowering interest paid on reserves can lower overnight market rates and encourage interest-sensitive spending.','Do not mechanically apply the limited-reserves money multiplier to an ample-reserves policy action.',
'Policy rate~The short-term interest rate targeted by a central bank.~政策利率|Administered rate~An interest rate set directly by the central bank.~管理利率|Open-market purchase~A central-bank purchase of securities that adds reserves.~公开市场购买',
[['A central bank buys securities. The immediate effect is generally:','More reserves and a larger monetary base.','Fewer reserves and a smaller base.','A direct increase in tax revenue.','An automatic identical rise in real GDP.','Payment for securities injects reserves into the banking system.','买入证券向银行体系注入准备金。'],['In an ample-reserves system, which action can lower overnight rates more directly?','Lowering an administered interest rate.','Adding reserves indefinitely with all administered rates unchanged.','Raising the tax rate.','Reducing government purchases.','Administered rates guide market rates when reserve supply is ample.','充裕准备金制度主要依靠管理利率引导市场利率。']]);
add('4.7','The Loanable Funds Market','可贷资金市场','Saving supplies funds and borrowing demands them.',
'Loanable-funds demand slopes down with the real interest rate.|Supply slopes up because higher real returns encourage saving.|National saving combines private and public saving.|In an open economy, investment equals national saving plus net capital inflow.|Saving changes, investment incentives and government borrowing alter equilibrium.',
'National saving of 400 plus net capital inflow of 50 finances domestic investment of 450.','Distinguish financial saving from spending on newly produced capital goods.',
'National saving~Private saving plus public saving.~国民储蓄|Loanable funds~Funds supplied by savers and demanded by borrowers.~可贷资金|Net capital inflow~Foreign purchases of domestic assets minus domestic purchases of foreign assets.~资本净流入',
[['Greater private saving, other things equal, shifts loanable-funds supply right and:','Lowers the real interest rate.','Raises the real interest rate.','Lowers the quantity of funds necessarily.','Eliminates investment.','A larger supply lowers the equilibrium borrowing cost.','储蓄增加使供给右移、实际利率下降。'],['Saving is 400 and net capital inflow is 50. Domestic investment equals:','450.','350.','400.','50.','Investment equals national saving plus net capital inflow.','投资等于国民储蓄加资本净流入。']]);
add('5.1','Fiscal and Monetary Policy Actions in the Short Run','短期财政与货币政策组合','Policy tools can reinforce or offset each other.',
'Expansionary fiscal and monetary policies can both support AD.|Contractionary policies can both restrain an inflationary gap.|Their effects on interest rates may oppose even when AD effects reinforce.|With conflicting policies, relative magnitudes matter for the net outcome.',
'Higher government purchases and lower policy rates both support spending; the final interest-rate change depends on the relative forces.','Do not label every outcome certain when policies push in opposite directions.',
'Policy mix~A combination of fiscal and monetary actions.~政策组合|Stabilization policy~Action intended to moderate short-run output fluctuations.~稳定政策|Interest-sensitive spending~Spending that responds to borrowing costs.~利率敏感支出',
[['Expansionary fiscal and expansionary monetary policy both tend to:','Increase aggregate demand.','Decrease aggregate demand.','Raise the policy rate necessarily.','Reduce output in the short run.','Both policies support spending through different channels.','两种扩张政策都支持总需求。'],['Fiscal expansion raises borrowing demand while monetary easing lowers rates. The net rate effect is:','Dependent on the relative effects.','Always an increase.','Always a decrease.','Always exactly zero.','Opposing influences cannot be ranked without more information.','相反作用的净效应取决于相对强弱。']]);
add('5.2','The Phillips Curve','菲利普斯曲线','Link inflation and unemployment in the short and long run.',
'The SRPC slopes downward for a given expected inflation rate.|Demand shocks move the economy along an SRPC.|Supply shocks and changed inflation expectations shift the SRPC.|The LRPC is vertical at the natural unemployment rate.|A change in the natural rate shifts LRPC; there is no permanent trade-off.',
'An adverse oil shock raises inflation and unemployment, shifting SRPC upward/rightward rather than moving along it.','Use inflation on the vertical axis, not the price level.',
'SRPC~The short-run relationship between inflation and unemployment for given expectations.~短期菲利普斯曲线|LRPC~A vertical curve at the natural rate of unemployment.~长期菲利普斯曲线|Inflation expectations~Beliefs about future inflation that influence wage and price setting.~通胀预期',
[['An adverse supply shock generally shifts the SRPC:','Upward/rightward.','Downward/leftward.','Nowhere; it is always a movement along it.','Into a horizontal LRPC.','Inflation and unemployment can both rise.','不利供给冲击使通胀和失业同时上升。'],['A positive demand shock with expectations initially unchanged causes:','Movement along SRPC toward higher inflation and lower unemployment.','A permanent fall in the natural rate.','A leftward LRPC shift automatically.','Higher inflation and higher unemployment along SRPC.','Demand shocks produce a short-run trade-off on the existing curve.','需求冲击引起沿既定SRPC移动。']]);
add('5.3','Money Growth and Inflation','货币增长与通胀','Persistent money growth must be compared with real output growth.',
'The equation of exchange is MV = PY.|Velocity measures how often money is used for final-output transactions.|With stable velocity, money growth beyond real-output growth produces inflation.|In the long run, money changes do not alone raise potential real output.|In growth-rate approximation, inflation ≈ money growth + velocity growth − real-output growth.',
'If money grows 6%, velocity is stable and real output grows 2%, inflation is approximately 4%.','Money growth does not translate one-for-one into inflation when real output or velocity changes.',
'Velocity~Nominal GDP divided by the money supply.~货币流通速度|Quantity theory~A framework linking money, velocity, prices and real output.~货币数量论|Monetary neutrality~The long-run independence of real output from changes in nominal money alone.~货币中性',
[['M=200, V=5 and Y=500. From MV=PY, P equals:','2.','5.','0.5.','10.','P = 200 × 5 / 500 = 2.','将MV除以Y得到价格水平。'],['Money grows 7%, velocity is stable and real output grows 3%. Approximate inflation is:','4%.','10%.','7%.','3%.','7 + 0 − 3 = 4%.','稳定流通速度下通胀约为货币增长减实际增长。']]);
add('5.4','Government Deficits and the National Debt','政府赤字与国债','Distinguish a yearly budget flow from accumulated borrowing.',
'A deficit occurs when government outlays exceed revenues.|A surplus occurs when revenues exceed outlays.|Deficits financed by borrowing add to national debt.|Debt service uses resources that could finance other public priorities.',
'Government outlays of 500 and revenue of 450 imply a deficit of 50; borrowing that amount increases outstanding debt by 50, other things equal.','The deficit is a flow per period; the debt is a stock at a date.',
'Budget deficit~Government outlays exceeding revenues during a period.~预算赤字|Budget surplus~Government revenues exceeding outlays during a period.~预算盈余|National debt~Outstanding accumulated government borrowing.~国债',
[['Revenue is 450 and outlays are 500. The budget has:','A deficit of 50.','A surplus of 50.','A debt of exactly 950.','A balanced budget.','Outlays exceed revenue by 50.','支出超过收入50。'],['Which is a stock variable?','National debt at year-end.','This year’s budget deficit.','Monthly tax receipts.','Annual government purchases.','Debt is measured at a point in time.','债务存量按时点衡量。']]);
add('5.5','Crowding Out','挤出效应','Government borrowing can reduce private investment.',
'Deficit financing can raise demand for loanable funds.|Higher real interest rates discourage interest-sensitive private spending.|Lower investment can reduce the capital stock relative to its alternative path.|Slower capital accumulation can reduce future growth.',
'In the borrower-demand convention, government borrowing shifts loanable-funds demand right and raises the real rate, reducing private investment.','When using national-saving supply instead, represent the deficit as lower public saving; do not count the same deficit on both curves.',
'Crowding out~Reduced private spending caused by higher interest rates from government borrowing.~挤出效应|Public saving~Government revenue minus government outlays in the simplified budget model.~公共储蓄|Capital accumulation~An increase in productive capital over time.~资本积累',
[['Government borrowing raises real interest rates. Private investment tends to:','Fall.','Rise automatically.','Equal government spending.','Become a transfer.','Higher borrowing costs make fewer private projects worthwhile.','融资成本上升抑制私人投资。'],['A possible long-run consequence of crowding out is:','Less capital accumulation and slower growth.','A larger capital stock necessarily.','Elimination of scarcity.','A guaranteed balanced budget.','Reduced investment can limit future productive capacity.','投资减少可能削弱未来生产能力。']]);
add('5.6','Economic Growth','经济增长','Productivity and resources determine sustainable living standards.',
'Real GDP per capita equals real GDP divided by population.|Output per worker measures labor productivity.|Physical capital, human capital and technology affect productivity.|Growth shifts PPC outward and LRAS right.|Higher aggregate employment can raise total output even without higher output per worker.',
'Real GDP rises 5% while population rises 2%; real GDP per capita grows about 3% (exactly 1.05/1.02 − 1 = 2.94%).','Total GDP growth and per-capita GDP growth are not identical.',
'Labor productivity~Real output per worker.~劳动生产率|Human capital~Productive knowledge and skills embodied in people.~人力资本|Real GDP per capita~Real GDP divided by population.~人均实际GDP',
[['Real GDP is 1000 and population is 50. Real GDP per capita is:','20.','50.','950.','50000.','1000 / 50 = 20.','实际GDP除以人口。'],['Improved worker training can increase growth by raising:','Human capital and productivity.','Only the price level.','Cyclical unemployment necessarily.','The nominal money stock necessarily.','Skills improve productive capacity.','技能提升人力资本和生产率。']]);
add('5.7','Public Policy and Economic Growth','公共政策与经济增长','Policies can influence incentives and productive capacity.',
'Infrastructure and research can improve productivity.|Education and training can build human capital.|Policies can affect labor-force participation and investment incentives.|Supply-side measures can influence both short-run AD and long-run capacity.|Evaluate the channel and assumptions rather than assuming every tax change guarantees growth.',
'A transport investment may initially raise AD through government purchases and later lower delivery costs, raising potential output.','A short-run spending increase is not by itself proof of a lasting LRAS shift.',
'Supply-side policy~Policy intended to influence production incentives or capacity.~供给侧政策|Infrastructure~Shared productive facilities such as transport and utilities.~基础设施|Research and development~Activity that creates new knowledge and production methods.~研发',
[['Which policy most directly builds human capital?','Effective education and training.','An increase in the nominal money stock alone.','A change in currency units.','A price ceiling on every good.','Education improves productive skills.','教育培训提高生产技能。'],['A productive infrastructure project can affect:','AD initially and productive capacity later.','Only money demand forever.','Only the unemployment definition.','Neither output nor costs.','Purchases add demand; useful infrastructure can raise productivity.','短期增加需求，长期可能提高生产率。']]);
add('6.1','Balance of Payments Accounts','国际收支账户','International transactions have offsetting accounting entries.',
'The current account includes net exports, net income from abroad and net unilateral transfers.|The capital and financial account records relevant international asset and capital transactions.|Credits represent inflows; debits represent outflows in the course convention.|Current account + capital and financial account = 0 in the simplified accounting framework.|A trade balance is only one part of the current account.',
'Net exports −40, net foreign income +10 and net transfers −5 produce a current-account balance of −35 and an offsetting CFA balance of +35.','A trade deficit and a current-account deficit are not always the same amount.',
'Current account~An account recording trade, net foreign income and net transfers.~经常账户|Financial account~An account recording cross-border financial asset transactions.~金融账户|Balance of payments~A system recording an economy’s international transactions.~国际收支',
[['The current account is −35. Under CA+CFA=0, CFA equals:','+35.','−35.','0.','+70.','The accounts offset in the simplified framework.','两账户余额互相抵消。'],['A resident purchases a foreign bond. This is primarily recorded as:','A financial asset outflow.','A goods export.','Government tax revenue.','Domestic consumption of a service.','A bond purchase is an asset transaction, not trade in goods.','购买外国债券属于金融资产流出。']]);
add('6.2','Exchange Rates','汇率','Always specify which currency is being priced.',
'An exchange rate is the price of one currency in another.|Appreciation raises a currency’s value; depreciation lowers it.|Reciprocal quotations describe the same exchange in opposite units.|A bilateral appreciation of one currency is depreciation of the other.',
'If €1 costs $1.25, then $1 buys €0.80. If €1 later costs $1.50, the euro has appreciated against the dollar.','Read the units before deciding whether a higher number means appreciation.',
'Exchange rate~The price of one currency expressed in another.~汇率|Appreciation~An increase in a currency’s value relative to another.~升值|Depreciation~A decrease in a currency’s value relative to another.~贬值',
[['If €1 costs $1.25, $1 buys:','€0.80.','€1.25.','€0.25.','€2.25.','The reciprocal of 1.25 is 0.80.','反向报价取倒数。'],['The dollar price of €1 rises from $1.20 to $1.40. The euro has:','Appreciated against the dollar.','Depreciated against the dollar.','Kept the same value.','Become a fixed exchange rate.','More dollars are required to buy a euro.','每欧元兑换更多美元意味着欧元升值。']]);
add('6.3','The Foreign Exchange Market','外汇市场','Currency demand and supply arise from cross-border purchases.',
'Foreign demand for domestic goods and assets creates demand for domestic currency.|Domestic purchases abroad create a supply of domestic currency.|The exchange rate adjusts until quantity demanded equals quantity supplied.|Draw the price of the currency in foreign units vertically and its quantity horizontally.|A shortage pressures the currency price upward; a surplus pressures it downward.',
'In the dollar market quoted as euros per dollar, more foreign demand for US assets shifts dollar demand right.','Do not reverse the currency being traded and the currency used to quote its price.',
'Currency demand~Desired purchases of a currency at each exchange rate.~货币兑换需求|Currency supply~Amounts of a currency offered for exchange at each rate.~货币兑换供给|Floating exchange rate~An exchange rate determined by market demand and supply.~浮动汇率',
[['Foreign buyers purchase more domestic exports. Demand for the domestic currency tends to:','Increase.','Decrease.','Become its supply.','Disappear.','Buyers need domestic currency to pay domestic sellers.','购买本国出口增加对本币的需求。'],['In a dollar market, the correct vertical-axis label could be:','Euros per dollar.','Quantity of dollars.','Real GDP.','Unemployment rate.','The vertical axis shows the price of dollars in the other currency.','纵轴表示每美元的外币价格。']]);
add('6.4','Effect of Changes in Policies and Economic Conditions on the Foreign Exchange Market','政策与经济条件对外汇市场的影响','Relative conditions change demand for currencies and assets.',
'Relative income, prices, preferences and asset returns can shift currency demand or supply.|Greater domestic demand for imports increases domestic currency supplied for exchange.|More attractive domestic assets increase demand for domestic currency.|Fiscal and monetary policy can affect currency values through interest rates and spending.|Separate currency-curve shifts from movements along a curve.',
'If domestic real returns rise relative to foreign returns with risk unchanged, investors buy more domestic assets and the domestic currency tends to appreciate.','Exchange-rate predictions depend on relative changes and other things being equal.',
'Relative return~An asset’s return compared with alternatives abroad.~相对收益率|Capital mobility~The ability of funds to move between countries.~资本流动性|Import demand~Domestic demand for goods and services produced abroad.~进口需求',
[['Domestic income rises, increasing imports with other factors unchanged. Domestic currency supply tends to:','Increase, putting downward pressure on its value.','Decrease, raising its value.','Remain fixed by definition.','Become the monetary base.','Residents exchange more domestic currency to buy foreign goods.','进口增加带来更多本币兑换供给。'],['Higher relative domestic asset returns tend to:','Increase demand for domestic currency.','Decrease all capital inflows.','Reduce domestic currency demand.','Eliminate exchange markets.','Foreign investors seek the more attractive domestic assets.','较高相对回报吸引境外投资者。']]);
add('6.5','Changes in the Foreign Exchange Market and Net Exports','外汇市场变化与净出口','Currency changes affect trade prices and aggregate demand.',
'Appreciation makes domestic exports more expensive to foreigners and imports cheaper to residents.|In the standard model, appreciation reduces net exports, other things equal.|Depreciation has the opposite directional effect on net exports.|Net exports are part of AD, so trade changes can affect short-run output and employment.',
'A domestic currency depreciation encourages foreign demand for domestic goods and discourages imports, tending to shift AD right.','These are other-things-equal model predictions, not guarantees that every trade balance changes immediately.',
'Trade balance~Exports minus imports of goods and services.~贸易差额|Export competitiveness~How attractive domestic goods are relative to foreign alternatives.~出口竞争力|Exchange-rate channel~The link from currency value through net exports to aggregate demand.~汇率传导渠道',
[['Domestic currency appreciation tends to make net exports:','Decrease.','Increase.','Remain fixed by accounting identity.','Equal government purchases.','Exports become relatively expensive and imports relatively cheap.','升值抑制出口并鼓励进口。'],['A depreciation that raises net exports tends to shift AD:','Right.','Left.','Nowhere because exports are excluded.','Into LRAS.','Net exports are a component of aggregate demand.','净出口增加使AD右移。']]);
add('6.6','Real Interest Rates and International Capital Flows','实际利率与国际资本流动','Financial funds respond to relative real returns.',
'Other things equal, funds flow toward higher real returns.|Capital inflows can increase demand for domestic currency and support appreciation.|Net capital inflows supplement national saving in financing investment.|Central-bank policy can affect rates and capital flows in the short run.|Connect loanable funds, exchange rates and net exports without confusing real and nominal rates.',
'If country A’s real rate rises relative to B’s with risk unchanged, funds tend to flow into A; A’s currency tends to appreciate and its net exports tend to fall.','Higher nominal interest alone does not guarantee a higher real return if inflation also rises.',
'Capital inflow~Foreign financing through purchases of domestic assets.~资本流入|Capital outflow~Domestic financing of foreign assets.~资本流出|Real return differential~The difference between inflation-adjusted returns across countries.~实际回报差',
[['Domestic real interest rises relative to foreign real interest, risk unchanged. Funds tend to:','Flow into the domestic economy.','Flow out of it.','Stop crossing borders.','Move only into goods exports.','Investors respond to relatively higher real returns.','资本倾向流入实际回报较高的经济体。'],['A nominal rate rises from 5% to 7% while expected inflation rises from 2% to 4%. The approximate expected real rate:','Remains 3%.','Rises to 5%.','Falls to 1%.','Becomes 11%.','Both nominal interest and expected inflation rise by 2 points.','名义利率与通胀预期等幅上升，实际利率不变。']]);
const unitTitles=['Basic Economic Concepts','Economic Indicators and the Business Cycle','National Income and Price Determination','Financial Sector','Long-Run Consequences of Stabilization Policies','Open Economy—International Trade and Finance'];
export const units=unitTitles.map((title,i)=>({id:i+1,title,color:i%2?'blue':'green',description:['Choices, opportunity costs and markets.','Measure output, prices and employment.','Explain shocks and stabilization with AD–AS.','Understand money, banking and interest rates.','Connect policy, inflation and long-run growth.','Trace trade, currencies and financial flows.'][i]}));
export const topics=rows.map(r=>({...r,unit:Number(r.id.split('.')[0]),logic:r.points.slice(0,3),explanation:r.zh+'：'+r.checks[0][6],conceptTitle:r.title,definition:r.summary}));
export const vocabulary=rows.flatMap(r=>r.terms.split('|').map((s,i)=>{const [term,definition,zh]=s.split('~');return {id:`ma-v-${r.id}-${i+1}`,topic:r.id,unit:Number(r.id[0]),term,definition,zh,example:r.example,mistake:r.mistake,source:'Econ Coach original · AP Macroeconomics'};}));
export const concepts=topics.flatMap(t=>[{id:`ma-c-${t.id}-1`,topic:t.id,unit:t.unit,title:t.title,definition:t.summary,points:t.points,logic:[],zh:t.zh,example:t.example,mistake:t.mistake},{id:`ma-c-${t.id}-2`,topic:t.id,unit:t.unit,title:`Apply: ${t.title}`,definition:t.checks[1][5],points:[t.points.at(-1)],logic:[],zh:t.checks[1][6],example:t.example,mistake:t.mistake,questionId:`ma-q-${t.id}-2`}]);
export const questions=rows.flatMap((r,ri)=>r.checks.map((q,i)=>{const offset=(ri+i)%4;const answers=q.slice(1,5);const ordered=answers.map((_,j)=>answers[(j-offset+4)%4]);return {id:`ma-q-${r.id}-${i+1}`,topic:r.id,unit:Number(r.id[0]),skill:/[0-9]/.test(q[0])?'calculation':'concept',stem:q[0],options:ordered.map((text,j)=>({key:'ABCD'[j],text,error:j===offset?null:/[0-9]/.test(q[0])?'M2':'C2'})),correct:'ABCD'[offset],explanation:q[5],zh:q[6],target:75,source:'Econ Coach original · AP Macroeconomics'};}));
// Merge source terms by normalized name; preserve our established card IDs.
import {sourceTerms,sourceQuestions} from './macro-imported.js?v=macro2';
const norm=s=>s.toLowerCase().replace(/[^a-z]/g,'');
const aliases={economicresources:'economicresource',productionpossibilitiescurve:'ppc',grossdomesticproduct:'gdp',consumerpriceindex:'cpi',marginalpropensitytoconsume:'mpc',marginalpropensitytosave:'mps',shortrunaggregatesupply:'sras',longrunaggregatesupply:'lras',shortrunphillipscurve:'srpc',longrunphillipscurve:'lrpc',nationalrateofunemployment:'naturalunemploymentrate',naturalrateofunemployment:'naturalunemploymentrate',nationalsavings:'nationalsaving',publicsavings:'publicsaving',automaticstabilizers:'automaticstabilizer',administeredinterestrates:'administeredrate',incomevelocityofmoney:'velocity',quantitytheoryofmoney:'quantitytheory',longrunselfadjustment:'selfadjustment',realwealtheffect:'wealtheffect',financialcapitalinflow:'capitalinflow',financialcapitaloutflow:'capitaloutflow',balanceoftrade:'tradebalance',potentialgdp:'potentialoutput'};
for(const t of sourceTerms){const n=aliases[norm(t.term)]||norm(t.term);const old=vocabulary.find(v=>norm(v.term)===n);const source={source:'Your macro vocabulary game',sourceUrl:'https://pjmarymeer-lab.github.io/macro-MCQ-practice/macro-matching-game/'};if(old){Object.assign(old,source);continue;}const topic=topics.find(x=>x.id===t.topic);vocabulary.push({id:'ma-source-v-'+n,topic:t.topic,unit:topic.unit,term:t.term,definition:t.definition,zh:'',example:topic.example,mistake:topic.mistake,...source});}
questions.push(...sourceQuestions);
